import { ComponentOptions, ComponentTypeEnum, ELayoutColumns, EnumGenerateMode, EnumLanguageCultureUI, IRenderingComponentData } from '@reactor-room/cms-models-lib';
import * as domain from './linked-list.domain';
describe('linked-list', () => {
  const components: IRenderingComponentData[] = [
    {
      isActive: true,
      _id: '61af494873f15d23a8d93e41',
      componentType: ComponentTypeEnum.CMS_NEXT_CMS_LAYOUT_RENDERING,
      commonSettings: {
        border: {
          corner: {
            topLeft: 0,
            topRight: 0,
            bottomLeft: 0,
            bottomRight: 0,
          },
          color: '',
          opacity: 100,
          thickness: 0,
          position: {
            left: false,
            top: false,
            right: false,
            bottom: false,
          },
        },
        shadow: {
          isShadow: false,
          color: '',
          opacity: 100,
          xAxis: 0,
          yAxis: 0,
          distance: 0,
          blur: 0,
        },
        hover: {
          textHover: '',
          style: '',
        },
        effect: {
          scrollEffect: '',
          xAxis: 0,
          yAxis: 0,
          isStretch: false,
          margin: 0,
        },
        background: {
          currentStyle: 'COLOR',
          layoutSettingBackgroundColorForm: {
            color: '',
            opacity: 100,
          },
          layoutSettingBackgroundImageForm: {
            imgUrl: '',
            position: 'center center',
            imageScale: 'unset',
            opacity: 100,
            colorOverlay: '',
            colorOverlayOpacity: 100,
            width: null,
            height: null,
            repeat: false,
          },
          layoutSettingBackgroundVideoForm: {
            videoUrl: '',
            position: 'center center',
            playInLoop: false,
            videoSpeed: 1,
            videoScale: 'unset',
            opacity: 100,
            colorOverlay: '',
            colorOverlayOpacity: 100,
            width: null,
            height: null,
          },
        },
        advance: {
          margin: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
          padding: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
          horizontalPosition: 'flex-start',
          verticalPosition: 'flex-start',
        },
        customize: {
          cssStyle: '',
          elementId: '',
        },
      },
      options: {
        setting: {
          column: ELayoutColumns.FIVE_FIVE_COLUMN,
          gap: 20,
        },
        containerSettings: [
          {
            border: {
              corner: {
                topLeft: 0,
                topRight: 0,
                bottomLeft: 0,
                bottomRight: 0,
              },
              color: '',
              opacity: 100,
              thickness: 0,
              position: {
                left: false,
                top: false,
                right: false,
                bottom: false,
              },
            },
            shadow: {
              isShadow: false,
              color: '',
              opacity: 100,
              xAxis: 0,
              yAxis: 0,
              distance: 0,
              blur: 0,
            },
            hover: {
              textHover: '',
              style: '',
            },
            effect: {
              scrollEffect: '',
              xAxis: 0,
              yAxis: 0,
              isStretch: false,
              margin: 0,
            },
            background: {
              currentStyle: 'COLOR',
              layoutSettingBackgroundColorForm: {
                color: '',
                opacity: 100,
              },
              layoutSettingBackgroundImageForm: {
                imgUrl: '',
                position: 'center center',
                imageScale: 'unset',
                opacity: 100,
                colorOverlay: '',
                colorOverlayOpacity: 100,
                width: null,
                height: null,
                repeat: false,
              },
              layoutSettingBackgroundVideoForm: {
                videoUrl: '',
                position: 'center center',
                playInLoop: false,
                videoSpeed: 1,
                videoScale: 'unset',
                opacity: 100,
                colorOverlay: '',
                colorOverlayOpacity: 100,
                width: null,
                height: null,
              },
            },
            advance: {
              margin: {
                left: 0,
                top: 0,
                right: 0,
                bottom: 0,
              },
              padding: {
                left: 0,
                top: 0,
                right: 0,
                bottom: 0,
              },
              horizontalPosition: 'flex-start',
              verticalPosition: 'flex-start',
            },
            customize: {
              cssStyle: '',
              elementId: '',
            },
          },
          {
            border: {
              corner: {
                topLeft: 0,
                topRight: 0,
                bottomLeft: 0,
                bottomRight: 0,
              },
              color: '',
              opacity: 100,
              thickness: 0,
              position: {
                left: false,
                top: false,
                right: false,
                bottom: false,
              },
            },
            shadow: {
              isShadow: false,
              color: '',
              opacity: 100,
              xAxis: 0,
              yAxis: 0,
              distance: 0,
              blur: 0,
            },
            hover: {
              textHover: '',
              style: '',
            },
            effect: {
              scrollEffect: '',
              xAxis: 0,
              yAxis: 0,
              isStretch: false,
              margin: 0,
            },
            background: {
              currentStyle: 'COLOR',
              layoutSettingBackgroundColorForm: {
                color: '',
                opacity: 100,
              },
              layoutSettingBackgroundImageForm: {
                imgUrl: '',
                position: 'center center',
                imageScale: 'unset',
                opacity: 100,
                colorOverlay: '',
                colorOverlayOpacity: 100,
                width: null,
                height: null,
                repeat: false,
              },
              layoutSettingBackgroundVideoForm: {
                videoUrl: '',
                position: 'center center',
                playInLoop: false,
                videoSpeed: 1,
                videoScale: 'unset',
                opacity: 100,
                colorOverlay: '',
                colorOverlayOpacity: 100,
                width: null,
                height: null,
              },
            },
            advance: {
              margin: {
                left: 0,
                top: 0,
                right: 0,
                bottom: 0,
              },
              padding: {
                left: 0,
                top: 0,
                right: 0,
                bottom: 0,
              },
              horizontalPosition: 'flex-start',
              verticalPosition: 'flex-start',
            },
            customize: {
              cssStyle: '',
              elementId: '',
            },
          },
          {
            border: {
              corner: {
                topLeft: 0,
                topRight: 0,
                bottomLeft: 0,
                bottomRight: 0,
              },
              color: '',
              opacity: 100,
              thickness: 0,
              position: {
                left: false,
                top: false,
                right: false,
                bottom: false,
              },
            },
            shadow: {
              isShadow: false,
              color: '',
              opacity: 100,
              xAxis: 0,
              yAxis: 0,
              distance: 0,
              blur: 0,
            },
            hover: {
              textHover: '',
              style: '',
            },
            effect: {
              scrollEffect: '',
              xAxis: 0,
              yAxis: 0,
              isStretch: false,
              margin: 0,
            },
            background: {
              currentStyle: 'COLOR',
              layoutSettingBackgroundColorForm: {
                color: '',
                opacity: 100,
              },
              layoutSettingBackgroundImageForm: {
                imgUrl: '',
                position: 'center center',
                imageScale: 'unset',
                opacity: 100,
                colorOverlay: '',
                colorOverlayOpacity: 100,
                width: null,
                height: null,
                repeat: false,
              },
              layoutSettingBackgroundVideoForm: {
                videoUrl: '',
                position: 'center center',
                playInLoop: false,
                videoSpeed: 1,
                videoScale: 'unset',
                opacity: 100,
                colorOverlay: '',
                colorOverlayOpacity: 100,
                width: null,
                height: null,
              },
            },
            advance: {
              margin: {
                left: 0,
                top: 0,
                right: 0,
                bottom: 0,
              },
              padding: {
                left: 0,
                top: 0,
                right: 0,
                bottom: 0,
              },
              horizontalPosition: 'flex-start',
              verticalPosition: 'flex-start',
            },
            customize: {
              cssStyle: '',
              elementId: '',
            },
          },
          {
            border: {
              corner: {
                topLeft: 0,
                topRight: 0,
                bottomLeft: 0,
                bottomRight: 0,
              },
              color: '',
              opacity: 100,
              thickness: 0,
              position: {
                left: false,
                top: false,
                right: false,
                bottom: false,
              },
            },
            shadow: {
              isShadow: false,
              color: '',
              opacity: 100,
              xAxis: 0,
              yAxis: 0,
              distance: 0,
              blur: 0,
            },
            hover: {
              textHover: '',
              style: '',
            },
            effect: {
              scrollEffect: '',
              xAxis: 0,
              yAxis: 0,
              isStretch: false,
              margin: 0,
            },
            background: {
              currentStyle: 'COLOR',
              layoutSettingBackgroundColorForm: {
                color: '',
                opacity: 100,
              },
              layoutSettingBackgroundImageForm: {
                imgUrl: '',
                position: 'center center',
                imageScale: 'unset',
                opacity: 100,
                colorOverlay: '',
                colorOverlayOpacity: 100,
                width: null,
                height: null,
                repeat: false,
              },
              layoutSettingBackgroundVideoForm: {
                videoUrl: '',
                position: 'center center',
                playInLoop: false,
                videoSpeed: 1,
                videoScale: 'unset',
                opacity: 100,
                colorOverlay: '',
                colorOverlayOpacity: 100,
                width: null,
                height: null,
              },
            },
            advance: {
              margin: {
                left: 0,
                top: 0,
                right: 0,
                bottom: 0,
              },
              padding: {
                left: 0,
                top: 0,
                right: 0,
                bottom: 0,
              },
              horizontalPosition: 'flex-start',
              verticalPosition: 'flex-start',
            },
            customize: {
              cssStyle: '',
              elementId: '',
            },
          },
        ],
      },
      layoutID: null,
      layoutPosition: null,
      nextId: '61af494873f15d23a8d93e54',
    },
    {
      isActive: true,
      _id: '61af494873f15d23a8d93e54',
      componentType: ComponentTypeEnum.CMS_NEXT_CMS_TEXT_RENDERING,
      commonSettings: {
        border: {
          corner: {
            topLeft: 0,
            topRight: 0,
            bottomLeft: 0,
            bottomRight: 0,
          },
          color: '',
          opacity: 100,
          thickness: 0,
          position: {
            left: false,
            top: false,
            right: false,
            bottom: false,
          },
        },
        shadow: {
          isShadow: false,
          color: '',
          opacity: 100,
          xAxis: 0,
          yAxis: 0,
          distance: 0,
          blur: 0,
        },
        hover: {
          textHover: '',
          style: '',
        },
        effect: {
          scrollEffect: '',
          xAxis: 0,
          yAxis: 0,
          isStretch: false,
          margin: 0,
        },
        background: {
          currentStyle: 'COLOR',
          layoutSettingBackgroundColorForm: {
            color: '',
            opacity: 100,
          },
          layoutSettingBackgroundImageForm: {
            imgUrl: '',
            position: 'center center',
            imageScale: 'unset',
            opacity: 100,
            colorOverlay: '',
            colorOverlayOpacity: 100,
            width: null,
            height: null,
            repeat: false,
          },
          layoutSettingBackgroundVideoForm: {
            videoUrl: '',
            position: 'center center',
            playInLoop: false,
            videoSpeed: 1,
            videoScale: 'unset',
            opacity: 100,
            colorOverlay: '',
            colorOverlayOpacity: 100,
            width: null,
            height: null,
          },
        },
        advance: {
          margin: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
          padding: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
          horizontalPosition: 'flex-start',
          verticalPosition: 'flex-start',
        },
        customize: {
          cssStyle: '',
          elementId: '',
        },
      },
      options: {
        quillHTMLs: [
          {
            cultureUI: EnumLanguageCultureUI.TH,
            quillHTML: '',
          },
        ],
      },
      layoutID: '61af494873f15d23a8d93e41',
      layoutPosition: 0,
      nextId: '61af494873f15d23a8d93e66',
    },
    {
      isActive: true,
      _id: '61af494873f15d23a8d93e66',
      componentType: ComponentTypeEnum.CMS_NEXT_CMS_TEXT_RENDERING,
      commonSettings: {
        border: {
          corner: {
            topLeft: 0,
            topRight: 0,
            bottomLeft: 0,
            bottomRight: 0,
          },
          color: '',
          opacity: 100,
          thickness: 0,
          position: {
            left: false,
            top: false,
            right: false,
            bottom: false,
          },
        },
        shadow: {
          isShadow: false,
          color: '',
          opacity: 100,
          xAxis: 0,
          yAxis: 0,
          distance: 0,
          blur: 0,
        },
        hover: {
          textHover: '',
          style: '',
        },
        effect: {
          scrollEffect: '',
          xAxis: 0,
          yAxis: 0,
          isStretch: false,
          margin: 0,
        },
        background: {
          currentStyle: 'COLOR',
          layoutSettingBackgroundColorForm: {
            color: '',
            opacity: 100,
          },
          layoutSettingBackgroundImageForm: {
            imgUrl: '',
            position: 'center center',
            imageScale: 'unset',
            opacity: 100,
            colorOverlay: '',
            colorOverlayOpacity: 100,
            width: null,
            height: null,
            repeat: false,
          },
          layoutSettingBackgroundVideoForm: {
            videoUrl: '',
            position: 'center center',
            playInLoop: false,
            videoSpeed: 1,
            videoScale: 'unset',
            opacity: 100,
            colorOverlay: '',
            colorOverlayOpacity: 100,
            width: null,
            height: null,
          },
        },
        advance: {
          margin: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
          padding: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
          horizontalPosition: 'flex-start',
          verticalPosition: 'flex-start',
        },
        customize: {
          cssStyle: '',
          elementId: '',
        },
      },
      options: {
        quillHTMLs: [
          {
            cultureUI: EnumLanguageCultureUI.TH,
            quillHTML: '',
          },
        ],
      },
      layoutID: '61af494873f15d23a8d93e41',
      layoutPosition: 1,
      nextId: '61af499173f15d23a8d93e88',
    },
    {
      isActive: true,
      _id: '61af499173f15d23a8d93e88',
      componentType: ComponentTypeEnum.CMS_NEXT_CMS_TEXT_RENDERING,
      commonSettings: {
        border: {
          corner: {
            topLeft: 0,
            topRight: 0,
            bottomLeft: 0,
            bottomRight: 0,
          },
          color: '',
          opacity: 100,
          thickness: 0,
          position: {
            left: false,
            top: false,
            right: false,
            bottom: false,
          },
        },
        shadow: {
          isShadow: false,
          color: '',
          opacity: 100,
          xAxis: 0,
          yAxis: 0,
          distance: 0,
          blur: 0,
        },
        hover: {
          textHover: '',
          style: '',
        },
        effect: {
          scrollEffect: '',
          xAxis: 0,
          yAxis: 0,
          isStretch: false,
          margin: 0,
        },
        background: {
          currentStyle: 'COLOR',
          layoutSettingBackgroundColorForm: {
            color: '',
            opacity: 100,
          },
          layoutSettingBackgroundImageForm: {
            imgUrl: '',
            position: 'center center',
            imageScale: 'unset',
            opacity: 100,
            colorOverlay: '',
            colorOverlayOpacity: 100,
            width: null,
            height: null,
            repeat: false,
          },
          layoutSettingBackgroundVideoForm: {
            videoUrl: '',
            position: 'center center',
            playInLoop: false,
            videoSpeed: 1,
            videoScale: 'unset',
            opacity: 100,
            colorOverlay: '',
            colorOverlayOpacity: 100,
            width: null,
            height: null,
          },
        },
        advance: {
          margin: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
          padding: {
            left: 0,
            top: 0,
            right: 0,
            bottom: 0,
          },
          horizontalPosition: 'flex-start',
          verticalPosition: 'flex-start',
        },
        customize: {
          cssStyle: '',
          elementId: '',
        },
      },
      options: {
        quillHTMLs: [
          {
            cultureUI: EnumLanguageCultureUI.TH,
            quillHTML: '',
          },
        ],
      },
      layoutID: null,
      layoutPosition: null,
      nextId: null,
    },
  ];
  const startId = '61af494873f15d23a8d93e41';
  const mockOrder = [
    {
      _id: '61af494873f15d23a8d93e41',
      commonSettings: {
        advance: {
          horizontalPosition: 'flex-start',
          margin: {
            bottom: 0,
            left: 0,
            right: 0,
            top: 0,
          },
          padding: {
            bottom: 0,
            left: 0,
            right: 0,
            top: 0,
          },
          verticalPosition: 'flex-start',
        },
        background: {
          currentStyle: 'COLOR',
          layoutSettingBackgroundColorForm: {
            color: '',
            opacity: 100,
          },
          layoutSettingBackgroundImageForm: {
            colorOverlay: '',
            colorOverlayOpacity: 100,
            height: null,
            imageScale: 'unset',
            imgUrl: '',
            opacity: 100,
            position: 'center center',
            repeat: false,
            width: null,
          },
          layoutSettingBackgroundVideoForm: {
            colorOverlay: '',
            colorOverlayOpacity: 100,
            height: null,
            opacity: 100,
            playInLoop: false,
            position: 'center center',
            videoScale: 'unset',
            videoSpeed: 1,
            videoUrl: '',
            width: null,
          },
        },
        border: {
          color: '',
          corner: {
            bottomLeft: 0,
            bottomRight: 0,
            topLeft: 0,
            topRight: 0,
          },
          opacity: 100,
          position: {
            bottom: false,
            left: false,
            right: false,
            top: false,
          },
          thickness: 0,
        },
        customize: {
          cssStyle: '',
          elementId: '',
        },
        effect: {
          isStretch: false,
          margin: 0,
          scrollEffect: '',
          xAxis: 0,
          yAxis: 0,
        },
        hover: {
          style: '',
          textHover: '',
        },
        shadow: {
          blur: 0,
          color: '',
          distance: 0,
          isShadow: false,
          opacity: 100,
          xAxis: 0,
          yAxis: 0,
        },
      },
      componentType: 'cms-next-cms-layout-rendering',
      isActive: true,
      layoutID: null,
      layoutPosition: null,
      nextId: '61af494873f15d23a8d93e54',
      options: {
        containerSettings: [
          {
            advance: {
              horizontalPosition: 'flex-start',
              margin: {
                bottom: 0,
                left: 0,
                right: 0,
                top: 0,
              },
              padding: {
                bottom: 0,
                left: 0,
                right: 0,
                top: 0,
              },
              verticalPosition: 'flex-start',
            },
            background: {
              currentStyle: 'COLOR',
              layoutSettingBackgroundColorForm: {
                color: '',
                opacity: 100,
              },
              layoutSettingBackgroundImageForm: {
                colorOverlay: '',
                colorOverlayOpacity: 100,
                height: null,
                imageScale: 'unset',
                imgUrl: '',
                opacity: 100,
                position: 'center center',
                repeat: false,
                width: null,
              },
              layoutSettingBackgroundVideoForm: {
                colorOverlay: '',
                colorOverlayOpacity: 100,
                height: null,
                opacity: 100,
                playInLoop: false,
                position: 'center center',
                videoScale: 'unset',
                videoSpeed: 1,
                videoUrl: '',
                width: null,
              },
            },
            border: {
              color: '',
              corner: {
                bottomLeft: 0,
                bottomRight: 0,
                topLeft: 0,
                topRight: 0,
              },
              opacity: 100,
              position: {
                bottom: false,
                left: false,
                right: false,
                top: false,
              },
              thickness: 0,
            },
            customize: {
              cssStyle: '',
              elementId: '',
            },
            effect: {
              isStretch: false,
              margin: 0,
              scrollEffect: '',
              xAxis: 0,
              yAxis: 0,
            },
            hover: {
              style: '',
              textHover: '',
            },
            shadow: {
              blur: 0,
              color: '',
              distance: 0,
              isShadow: false,
              opacity: 100,
              xAxis: 0,
              yAxis: 0,
            },
          },
          {
            advance: {
              horizontalPosition: 'flex-start',
              margin: {
                bottom: 0,
                left: 0,
                right: 0,
                top: 0,
              },
              padding: {
                bottom: 0,
                left: 0,
                right: 0,
                top: 0,
              },
              verticalPosition: 'flex-start',
            },
            background: {
              currentStyle: 'COLOR',
              layoutSettingBackgroundColorForm: {
                color: '',
                opacity: 100,
              },
              layoutSettingBackgroundImageForm: {
                colorOverlay: '',
                colorOverlayOpacity: 100,
                height: null,
                imageScale: 'unset',
                imgUrl: '',
                opacity: 100,
                position: 'center center',
                repeat: false,
                width: null,
              },
              layoutSettingBackgroundVideoForm: {
                colorOverlay: '',
                colorOverlayOpacity: 100,
                height: null,
                opacity: 100,
                playInLoop: false,
                position: 'center center',
                videoScale: 'unset',
                videoSpeed: 1,
                videoUrl: '',
                width: null,
              },
            },
            border: {
              color: '',
              corner: {
                bottomLeft: 0,
                bottomRight: 0,
                topLeft: 0,
                topRight: 0,
              },
              opacity: 100,
              position: {
                bottom: false,
                left: false,
                right: false,
                top: false,
              },
              thickness: 0,
            },
            customize: {
              cssStyle: '',
              elementId: '',
            },
            effect: {
              isStretch: false,
              margin: 0,
              scrollEffect: '',
              xAxis: 0,
              yAxis: 0,
            },
            hover: {
              style: '',
              textHover: '',
            },
            shadow: {
              blur: 0,
              color: '',
              distance: 0,
              isShadow: false,
              opacity: 100,
              xAxis: 0,
              yAxis: 0,
            },
          },
          {
            advance: {
              horizontalPosition: 'flex-start',
              margin: {
                bottom: 0,
                left: 0,
                right: 0,
                top: 0,
              },
              padding: {
                bottom: 0,
                left: 0,
                right: 0,
                top: 0,
              },
              verticalPosition: 'flex-start',
            },
            background: {
              currentStyle: 'COLOR',
              layoutSettingBackgroundColorForm: {
                color: '',
                opacity: 100,
              },
              layoutSettingBackgroundImageForm: {
                colorOverlay: '',
                colorOverlayOpacity: 100,
                height: null,
                imageScale: 'unset',
                imgUrl: '',
                opacity: 100,
                position: 'center center',
                repeat: false,
                width: null,
              },
              layoutSettingBackgroundVideoForm: {
                colorOverlay: '',
                colorOverlayOpacity: 100,
                height: null,
                opacity: 100,
                playInLoop: false,
                position: 'center center',
                videoScale: 'unset',
                videoSpeed: 1,
                videoUrl: '',
                width: null,
              },
            },
            border: {
              color: '',
              corner: {
                bottomLeft: 0,
                bottomRight: 0,
                topLeft: 0,
                topRight: 0,
              },
              opacity: 100,
              position: {
                bottom: false,
                left: false,
                right: false,
                top: false,
              },
              thickness: 0,
            },
            customize: {
              cssStyle: '',
              elementId: '',
            },
            effect: {
              isStretch: false,
              margin: 0,
              scrollEffect: '',
              xAxis: 0,
              yAxis: 0,
            },
            hover: {
              style: '',
              textHover: '',
            },
            shadow: {
              blur: 0,
              color: '',
              distance: 0,
              isShadow: false,
              opacity: 100,
              xAxis: 0,
              yAxis: 0,
            },
          },
          {
            advance: {
              horizontalPosition: 'flex-start',
              margin: {
                bottom: 0,
                left: 0,
                right: 0,
                top: 0,
              },
              padding: {
                bottom: 0,
                left: 0,
                right: 0,
                top: 0,
              },
              verticalPosition: 'flex-start',
            },
            background: {
              currentStyle: 'COLOR',
              layoutSettingBackgroundColorForm: {
                color: '',
                opacity: 100,
              },
              layoutSettingBackgroundImageForm: {
                colorOverlay: '',
                colorOverlayOpacity: 100,
                height: null,
                imageScale: 'unset',
                imgUrl: '',
                opacity: 100,
                position: 'center center',
                repeat: false,
                width: null,
              },
              layoutSettingBackgroundVideoForm: {
                colorOverlay: '',
                colorOverlayOpacity: 100,
                height: null,
                opacity: 100,
                playInLoop: false,
                position: 'center center',
                videoScale: 'unset',
                videoSpeed: 1,
                videoUrl: '',
                width: null,
              },
            },
            border: {
              color: '',
              corner: {
                bottomLeft: 0,
                bottomRight: 0,
                topLeft: 0,
                topRight: 0,
              },
              opacity: 100,
              position: {
                bottom: false,
                left: false,
                right: false,
                top: false,
              },
              thickness: 0,
            },
            customize: {
              cssStyle: '',
              elementId: '',
            },
            effect: {
              isStretch: false,
              margin: 0,
              scrollEffect: '',
              xAxis: 0,
              yAxis: 0,
            },
            hover: {
              style: '',
              textHover: '',
            },
            shadow: {
              blur: 0,
              color: '',
              distance: 0,
              isShadow: false,
              opacity: 100,
              xAxis: 0,
              yAxis: 0,
            },
          },
        ],
        setting: {
          column: 'repeat(2, 1fr)',
          gap: 20,
        },
      },
    },
    {
      _id: '61af494873f15d23a8d93e54',
      commonSettings: {
        advance: {
          horizontalPosition: 'flex-start',
          margin: {
            bottom: 0,
            left: 0,
            right: 0,
            top: 0,
          },
          padding: {
            bottom: 0,
            left: 0,
            right: 0,
            top: 0,
          },
          verticalPosition: 'flex-start',
        },
        background: {
          currentStyle: 'COLOR',
          layoutSettingBackgroundColorForm: {
            color: '',
            opacity: 100,
          },
          layoutSettingBackgroundImageForm: {
            colorOverlay: '',
            colorOverlayOpacity: 100,
            height: null,
            imageScale: 'unset',
            imgUrl: '',
            opacity: 100,
            position: 'center center',
            repeat: false,
            width: null,
          },
          layoutSettingBackgroundVideoForm: {
            colorOverlay: '',
            colorOverlayOpacity: 100,
            height: null,
            opacity: 100,
            playInLoop: false,
            position: 'center center',
            videoScale: 'unset',
            videoSpeed: 1,
            videoUrl: '',
            width: null,
          },
        },
        border: {
          color: '',
          corner: {
            bottomLeft: 0,
            bottomRight: 0,
            topLeft: 0,
            topRight: 0,
          },
          opacity: 100,
          position: {
            bottom: false,
            left: false,
            right: false,
            top: false,
          },
          thickness: 0,
        },
        customize: {
          cssStyle: '',
          elementId: '',
        },
        effect: {
          isStretch: false,
          margin: 0,
          scrollEffect: '',
          xAxis: 0,
          yAxis: 0,
        },
        hover: {
          style: '',
          textHover: '',
        },
        shadow: {
          blur: 0,
          color: '',
          distance: 0,
          isShadow: false,
          opacity: 100,
          xAxis: 0,
          yAxis: 0,
        },
      },
      componentType: 'cms-next-cms-text-rendering',
      isActive: true,
      layoutID: '61af494873f15d23a8d93e41',
      layoutPosition: 0,
      nextId: '61af494873f15d23a8d93e66',
      options: {
        quillHTMLs: [
          {
            cultureUI: EnumLanguageCultureUI.TH,
            quillHTML: '',
          },
        ],
      },
      prevId: '61af494873f15d23a8d93e41',
    },
    {
      _id: '61af494873f15d23a8d93e66',
      commonSettings: {
        advance: {
          horizontalPosition: 'flex-start',
          margin: {
            bottom: 0,
            left: 0,
            right: 0,
            top: 0,
          },
          padding: {
            bottom: 0,
            left: 0,
            right: 0,
            top: 0,
          },
          verticalPosition: 'flex-start',
        },
        background: {
          currentStyle: 'COLOR',
          layoutSettingBackgroundColorForm: {
            color: '',
            opacity: 100,
          },
          layoutSettingBackgroundImageForm: {
            colorOverlay: '',
            colorOverlayOpacity: 100,
            height: null,
            imageScale: 'unset',
            imgUrl: '',
            opacity: 100,
            position: 'center center',
            repeat: false,
            width: null,
          },
          layoutSettingBackgroundVideoForm: {
            colorOverlay: '',
            colorOverlayOpacity: 100,
            height: null,
            opacity: 100,
            playInLoop: false,
            position: 'center center',
            videoScale: 'unset',
            videoSpeed: 1,
            videoUrl: '',
            width: null,
          },
        },
        border: {
          color: '',
          corner: {
            bottomLeft: 0,
            bottomRight: 0,
            topLeft: 0,
            topRight: 0,
          },
          opacity: 100,
          position: {
            bottom: false,
            left: false,
            right: false,
            top: false,
          },
          thickness: 0,
        },
        customize: {
          cssStyle: '',
          elementId: '',
        },
        effect: {
          isStretch: false,
          margin: 0,
          scrollEffect: '',
          xAxis: 0,
          yAxis: 0,
        },
        hover: {
          style: '',
          textHover: '',
        },
        shadow: {
          blur: 0,
          color: '',
          distance: 0,
          isShadow: false,
          opacity: 100,
          xAxis: 0,
          yAxis: 0,
        },
      },
      componentType: 'cms-next-cms-text-rendering',
      isActive: true,
      layoutID: '61af494873f15d23a8d93e41',
      layoutPosition: 1,
      nextId: '61af499173f15d23a8d93e88',
      options: {
        quillHTMLs: [
          {
            cultureUI: EnumLanguageCultureUI.TH,
            quillHTML: '',
          },
        ],
      },
      prevId: '61af494873f15d23a8d93e54',
    },
    {
      _id: '61af499173f15d23a8d93e88',
      commonSettings: {
        advance: {
          horizontalPosition: 'flex-start',
          margin: {
            bottom: 0,
            left: 0,
            right: 0,
            top: 0,
          },
          padding: {
            bottom: 0,
            left: 0,
            right: 0,
            top: 0,
          },
          verticalPosition: 'flex-start',
        },
        background: {
          currentStyle: 'COLOR',
          layoutSettingBackgroundColorForm: {
            color: '',
            opacity: 100,
          },
          layoutSettingBackgroundImageForm: {
            colorOverlay: '',
            colorOverlayOpacity: 100,
            height: null,
            imageScale: 'unset',
            imgUrl: '',
            opacity: 100,
            position: 'center center',
            repeat: false,
            width: null,
          },
          layoutSettingBackgroundVideoForm: {
            colorOverlay: '',
            colorOverlayOpacity: 100,
            height: null,
            opacity: 100,
            playInLoop: false,
            position: 'center center',
            videoScale: 'unset',
            videoSpeed: 1,
            videoUrl: '',
            width: null,
          },
        },
        border: {
          color: '',
          corner: {
            bottomLeft: 0,
            bottomRight: 0,
            topLeft: 0,
            topRight: 0,
          },
          opacity: 100,
          position: {
            bottom: false,
            left: false,
            right: false,
            top: false,
          },
          thickness: 0,
        },
        customize: {
          cssStyle: '',
          elementId: '',
        },
        effect: {
          isStretch: false,
          margin: 0,
          scrollEffect: '',
          xAxis: 0,
          yAxis: 0,
        },
        hover: {
          style: '',
          textHover: '',
        },
        shadow: {
          blur: 0,
          color: '',
          distance: 0,
          isShadow: false,
          opacity: 100,
          xAxis: 0,
          yAxis: 0,
        },
      },
      componentType: 'cms-next-cms-text-rendering',
      isActive: true,
      layoutID: null,
      layoutPosition: null,
      nextId: null,
      options: {
        quillHTMLs: [
          {
            cultureUI: EnumLanguageCultureUI.TH,
            quillHTML: '',
          },
        ],
      },
      prevId: '61af494873f15d23a8d93e66',
    },
  ];
  test('sortedLinkedList', () => {
    const ordered = domain.sortedLinkedList(components, startId, EnumGenerateMode.PAGECOMPONENT);
    expect(ordered).toStrictEqual(mockOrder);
  });
});
