export enum PageSettingType {
  CUSTOMER_CLOSED_REASON = 'CUSTOMER_CLOSED_REASON',
  CUSTOMER_SLA_TIME = 'CUSTOMER_SLA_TIME',
  TERMS_AND_CONDITION = 'TERMS_AND_CONDITION',
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  DATA_USE = 'DATA_USE',
  WORKING_HOURS = 'WORKING_HOURS',
  MESSAGE_TRACK = 'MESSAGE_TRACK',
  QUICKPAY_WEBHOOK = 'QUICKPAY_WEBHOOK',
  LOGISTIC_SYSTEM = 'LOGISTIC_SYSTEM',
}

export enum EPageMessageTrackMode {
  TRACK_BY_TAG = 'TRACK_BY_TAG',
  TRACK_BY_ASSIGNEE = 'TRACK_BY_ASSIGNEE',
}

export const WorkhourShopStatus = {
  OPEN: false,
  CLOSE: true,
};
