// This file is autogenerated by lib/feature-plugin.js

import { expose } from 'comlink';
import { svgo } from './svgo';
import resize from './resize';

const exports = {
  resize(...args: Parameters<typeof resize>): ReturnType<typeof resize> {
    return resize(...args);
  },
  svgo(...args: Parameters<typeof svgo>): ReturnType<typeof svgo> {
    return svgo(...args);
  },
};
export type ProcessorWorkerApi = typeof exports;
// 'as any' to work around the way our client code has insight into worker code
expose(exports, self as any);
