apiVersion: apps/v1
kind: Deployment
metadata:
  name: plusmar-backend-_ENV_
  namespace: plusmar
spec:
  replicas: _SIZE_
  selector:
    matchLabels:
      app: plusmar-backend-_ENV_
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: plusmar-backend-_ENV_
      annotations:
        'cluster-autoscaler.kubernetes.io/safe-to-evict': 'false'
    spec:
      containers:
        - name: plusmar-backend-_ENV_
          image: git.itopplus.com:5000/plusmar/backend:_TAG_
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 3333
          readinessProbe:
            tcpSocket:
              port: 3333
          resources:
            requests:
              cpu: '125m'
              memory: '128Mi'
          env:
            - name: NODE_ENV
              value: '_ENV_'
            - name: MONGODB
              value: '_MONGODB_'
            - name: PG_URL_READ
              value: '_PG_URL_READ_'
            - name: PG_URL_WRITE
              value: '_PG_URL_WRITE_'
            - name: REDIS_HOST
              value: '_REDIS_HOST_'
            - name: WEB_VIEW_URL
              value: '_WEB_VIEW_URL_'
            - name: BACKEND_URL
              value: '_BACKEND_URL_'
            - name: ORIGIN
              value: '_ORIGIN_'
            - name: ADMINORIGIN
              value: '_ADMINORIGIN_'
            - name: PAYAL_AUTH_API
              value: '_PAYAL_AUTH_API_'
            - name: PAYPAL_ORDER_API
              value: '_PAYPAL_ORDER_API_'
            - name: WEBVIEWKEY
              value: '_WEBVIEWKEY_'
            - name: NLP_API
              value: '_NLP_API_'
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: './assets/static/AUTH.json'
            - name: 'PAYMENT_2C2P_VERSION'
              value: '8.5'
            - name: 'PAYMENT_2C2P_REQUEST_3DS'
              value: 'Y'
            - name: 'payment2C2PRedirectApi'
              value: ''
            - name: 'FLASH_EXPRESS_KEY'
              value: '_FLASH_EXPRESS_KEY_'
            - name: 'J_AND_T_KEY'
              value: '_J_AND_T_KEY_'
            - name: 'TZ'
              value: 'Asia/Bangkok'
      imagePullSecrets:
        - name: gitlabsecret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: plusmar-backend-_ENV_-service
  name: plusmar-backend-_ENV_-service
  namespace: plusmar
  annotations:
    cloud.google.com/load-balancer-type: 'Internal'
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3333
  selector:
    app: plusmar-backend-_ENV_
