apiVersion: apps/v1
kind: Deployment
metadata:
  name: plusmar-cron-_ENV_
  namespace: plusmar
spec:
  replicas: _SIZE_
  selector:
    matchLabels:
      app: plusmar-cron-_ENV_
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: plusmar-cron-_ENV_
      annotations:
        'cluster-autoscaler.kubernetes.io/safe-to-evict': 'false'
    spec:
      containers:
        - name: plusmar-cron-_ENV_
          image: git.itopplus.com:5000/plusmar/cron:_TAG_
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '125m'
              memory: '128Mi'
          env:
            - name: NODE_ENV
              value: '_ENV_'
            - name: MONGODB
              value: '_MONGODB_'
            - name: PG_URL_READ
              value: '_PG_URL_READ_'
            - name: PG_URL_WRITE
              value: '_PG_URL_WRITE_'
            - name: REDIS_HOST
              value: '_REDIS_HOST_'
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: './assets/AUTH.json'
      imagePullSecrets:
        - name: gitlabsecret
