apiVersion: apps/v1
kind: Deployment
metadata:
  name: plusmar-web-_ENV_
  namespace: plusmar
spec:
  replicas: _SIZE_
  selector:
    matchLabels:
      app: plusmar-web-_ENV_
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: plusmar-web-_ENV_
      annotations:
        'cluster-autoscaler.kubernetes.io/safe-to-evict': 'true'
    spec:
      containers:
        - name: plusmar-web-_ENV_
          image: git.itopplus.com:5000/plusmar/web:_TAG_
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
      imagePullSecrets:
        - name: gitlabsecret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: plusmar-web-_ENV_-service
  name: plusmar-web-_ENV_-service
  namespace: plusmar
  annotations:
    cloud.google.com/load-balancer-type: 'Internal'
spec:
  type: LoadBalancer
  ports:
    - name: plusmar-web-_ENV_-port
      port: 8080
      targetPort: 3000
  selector:
    app: plusmar-web-_ENV_
