apiVersion: apps/v1
kind: Deployment
metadata:
  name: plusmar-webhook-_ENV_
  namespace: plusmar
spec:
  replicas: _SIZE_
  selector:
    matchLabels:
      app: plusmar-webhook-_ENV_
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: plusmar-webhook-_ENV_
      annotations:
        'cluster-autoscaler.kubernetes.io/safe-to-evict': 'false'
    spec:
      containers:
        - name: plusmar-webhook-_ENV_
          image: git.itopplus.com:5000/plusmar/webhook:_TAG_
          imagePullPolicy: Always
          ports:
            - containerPort: 8740
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /checkstatus
              port: 8740
          readinessProbe:
            tcpSocket:
              port: 8740
          resources:
            requests:
              cpu: '125m'
              memory: '128Mi'
          env:
            - name: NODE_ENV
              value: '_ENV_'
            - name: MONGODB
              value: '_MONGODB_'
            - name: PG_URL_READ
              value: '_PG_URL_READ_'
            - name: PG_URL_WRITE
              value: '_PG_URL_WRITE_'
            - name: REDIS_HOST
              value: '_REDIS_HOST_'
            - name: WEB_VIEW_URL
              value: '_WEB_VIEW_URL_'
            - name: WEBVIEWKEY
              value: '_WEBVIEWKEY_'
            - name: BACKEND_URL
              value: '_BACKEND_URL_'
            - name: SUBSCRIPTION_NAME
              value: '_SUBSCRIPTION_NAME_'
            - name: LINESUBSCRIPTION
              value: '_LINESUBSCRIPTION_'
            - name: PAYAL_AUTH_API
              value: '_PAYAL_AUTH_API_'
            - name: PAYPAL_ORDER_API
              value: '_PAYPAL_ORDER_API_'
            - name: NLP_API
              value: '_NLP_API_'
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: './assets/AUTH.json'
      imagePullSecrets:
        - name: gitlabsecret
