export enum IFacebookPipelineStepTemplateType {
  MEDIA = 'media',
  GENERIC = 'generic',
  RECEIPT = 'receipt',
  BUTTON = 'button',
  ORDER_TRACKING = 'ordertracking',
}

export enum PipelineStepTypeEnum {
  ORDER = 'ORDER',
  SELECT_BANK = 'SELECT_BANK',
  // SELECT_ORDER = 'SELECT_ORDER',
  ORDER_RECEIPT = 'ORDER_RECEIPT',
  SELECT_PAYMENT = 'SELECT_PAYMENT',
  SELECT_LOGISTIC = 'SELECT_LOGISTIC',
  ORDER_RECEIPT_ACTIONS = 'ORDER_RECEIPT_ACTIONS',
  ORDER_STATUS_RECEIVED = 'ORDER_STATUS_RECEIVED',
  ORDER_STATUS_COMPLETED = 'ORDER_STATUS_COMPLETED',
  EDIT_SHIPPING_ADDRESS = 'EDIT_SHIPPING_ADDRESS',
  CONFIRM_SHIPPING_ADDRESS = 'CONFIRM_SHIPPING_ADDRESS',
  CUSTOM_FORM = 'CUSTOM_FORM',
  SELECT_PRODUCT_NO_VARIANT = 'SELECT_PRODUCT_NO_VARIANT',
}
