export enum EnumPurchaseOrderError {
  WEIGHT_OUT_OF_RANGE = 'WEIGHT_OUT_OF_RANGE',
}

export enum EnumCustomStep {
  FOLLOW = 'Step 1 : Follow',
  WAITING_FOR_PAYMENT = 'Step 2 : Waiting for payment',
  CONFIRM_PAYMENT = 'Step 3 : Confirm payment',
  WAITING_FOR_SHIPMENT = 'Step 4 : Waiting for shipment',
  CLOSED = 'Step 5 : Close sale',
  REJECT = 'Rejected',
}
export enum EnumCustomStepIndex {
  FOLLOW = 1,
  WAITING_FOR_PAYMENT = 2,
  CONFIRM_PAYMENT = 3,
  WAITING_FOR_SHIPMENT = 4,
  CLOSED = 5,
}

export const EnumStepFollow = 1;
export const EnumStepWaitingForPayment = 2;
export const EnumStepConfirmPayment = 3;
export const EnumStepWaitingForShippment = 4;
export const EnumStepClosed = 5;
// export enum StepFollow  = {
//   '1': 'FOLLOW',
//   '2': 'WAITING_FOR_PAYMENT',
//   '3': 'CONFIRM_PAYMENT',
//   '4': 'WAITING_FOR_SHIPMENT',
//   '5': 'CLOSED',
// };
export enum EnumButtonTextNextStep {
  FOLLOW = 'Waiting for payment',
  WAITING_FOR_PAYMENT = 'Confirm Payment',
  CONFIRM_PAYMENT = 'Waiting for shipment',
  WAITING_FOR_SHIPMENT = 'Close sale',
  CLOSED = 'Close sale',
}

export enum EnumFollowRoute {
  FOLLOW = 'follow',
  WAITING_FOR_PAYMENT = 'pending',
  CONFIRM_PAYMENT = 'confirm-payment',
  WAITING_FOR_SHIPMENT = 'unfulfilled',
  CLOSED = 'close-sales',
}

export enum EnumPurchasingPayloadType {
  // SELECT_ORDER = 'SELECT_ORDER',
  SEND_CART = 'SEND_CART',
  SEND_RECEIPT = 'SEND_RECEIPT',
  UPDATE_CART = 'UPDATE_CART',
  CONFIRM_ORDER = 'CONFIRM_ORDER',
  RECEIVE_ORDER_CONFIRMATION = 'RECEIVE_ORDER_CONFIRMATION',
  RECEIVE_ORDER_CONFIRMATION_FLAT_RATE = 'RECEIVE_ORDER_CONFIRMATION_FLAT_RATE',
  COMBINE_LOGISTIC_PAYMENT = 'COMBINE_LOGISTIC_PAYMENT',
  GET_PAYPAL_INFO = 'GET_PAYPAL_INFO',
  LOGISTIC_SELECTOR = 'LOGISTIC_SELECTOR',
  PAYMENT_SELECTOR = 'PAYMENT_SELECTOR',
  SEND_PAYMENT = 'SEND_PAYMENT',
  SEND_BANK_ACCOUNT = 'SEND_BANK_ACCOUNT',
  SEND_PAYPAL_PAYMENT = 'SEND_PAYPAL_PAYMENT',
  SEND_KBANK_PAYMENT = 'SEND_KBANK_PAYMENT',
  SEND_PAY_SOLUTION_PAYMENT = 'SEND_PAY_SOLUTION_PAYMENT',
  GET_OMISE_ORDER_INFO = 'GET_OMISE_ORDER_INFO',
  SUBMIT_OMISE_PAYMENT = 'SUBMIT_OMISE_PAYMENT',
  SEND_2C2P_PAYMENT = 'SEND_2C2P_PAYMENT',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  // 2C2P
  SUBMIT_2C2P_PAYMENT_SUCCESS = 'SUBMIT_2C2P_PAYMENT_SUCCESS', // 000
  SUBMIT_2C2P_PAYMENT_PENDING = 'SUBMIT_2C2P_PAYMENT_PENDING', // 001
  SUBMIT_2C2P_PAYMENT_REJECTED = 'SUBMIT_2C2P_PAYMENT_REJECTED', // 002
  SUBMIT_2C2P_PAYMENT_CANCELED = 'SUBMIT_2C2P_PAYMENT_CANCELED', // 003
  SUBMIT_2C2P_PAYMENT_FAIL = 'SUBMIT_2C2P_PAYMENT_FAIL', // 999
  SUBMIT_OMISE_PAYMENT_SUCCESS = 'SUBMIT_OMISE_PAYMENT_SUCCESS', // 000
  SUBMIT_OMISE_PAYMENT_PENDING = 'SUBMIT_OMISE_PAYMENT_PENDING', // 000
  SUBMIT_OMISE_PAYMENT_FAILED = 'SUBMIT_OMISE_PAYMENT_FAILED', // 000
  CHECK_ADDRESS = 'CHECK_ADDRESS',
  CHECK_ADDRESS_COD = 'CHECK_ADDRESS_COD',
  ADDRESS_EDITING = 'ADDRESS_EDITING',
  SEND_TRACKING_NUMBER = 'SEND_TRACKING_NUMBER',
  SEND_TRACKING_NUMBER_COD = 'SEND_TRACKING_NUMBER_COD',
  SELECT_SINGLE_PRODUCT = 'SELECT_SINGLE_PRODUCT',
  SELECT_MULTIPLE_PRODUCT = 'SELECT_MULTIPLE_PRODUCT',
  EXAMPLE = 'EXAMPLE',
  // PAYMENT
  REPEAT_SEND_CHECKOUT = 'REPEAT_SEND_CHECKOUT',
  CHECKOUT_PAYPAL = 'CHECKOUT_PAYPAL',
  CHECKOUT_2C2P = 'CHECKOUT_2C2P',
  CHECKOUT_OMISE = 'CHECKOUT_OMISE',
  GENEREIC_PAYMENT_SUCCESS = 'GENEREIC_PAYMENT_SUCCESS',
  GENEREIC_PAYMENT_FAILED = 'GENEREIC_PAYMENT_FAILED',
  OMISE_REDIRECT = 'OMISE_REDIRECT',
  QUICK_PAY_PAYMENT_PREVIEW = 'QUICK_PAY_PAYMENT_PREVIEW',
  SEND_PRODUCT_CATALOG = 'SEND_PRODUCT_CATALOG',
  SEND_PRODUCT_CATALOG_FILTER = 'SEND_PRODUCT_CATALOG_FILTER',
  SEND_PRODUCT_CATALOG_VARIANT = 'SEND_PRODUCT_CATALOG_VARIANT',
  SEND_PRODUCT_CATALOG_CART = 'SEND_PRODUCT_CATALOG_CART',
}

export enum EnumHandleResponseMessageType {
  ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART',
  ADD_PRODUCT_VIA_SHARE_LINK = 'ADD_PRODUCT_VIA_SHARE_LINK',
  RESPONSE_CONFIRM_ORDER = 'RESPONSE_CONFIRM_ORDER',
  CONFIRM_PAYMENT_SELECTION = 'CONFIRM_PAYMENT_SELECTION',
  CHECK_PRODUCT_SUFFICIENT = 'CHECK_PRODUCT_SUFFICIENT',
  VERIFY_ORDER_CONTEXT = 'VERIFY_ORDER_CONTEXT',
  UPDATE_DELIVERY_ADDRESS = 'UPDATE_DELIVERY_ADDRESS',
  GET_PRODUCT_IN_CART = 'GET_PRODUCT_IN_CART',
  RELOAD_CART_CONTEXT = 'RELOAD_CART_CONTEXT',
  SELECT_PAYMENT_METHOD = 'SELECT_PAYMENT_METHOD',
  SUBMIT_PAYMENT = 'SUBMIT_PAYMENT', // ONLY_PROCEED_BY_UI_STEP3,
  SUBMIT_PAYPAL_PAYMENT = 'SUBMIT_PAYPAL_PAYMENT',
  SUBMIT_PAYPAL_PAYMENT_APPROVE = 'SUBMIT_PAYPAL_PAYMENT_APPROVE',
  SUBMIT_PAYPAL_PAYMENT_ERROR = 'SUBMIT_PAYPAL_PAYMENT_ERROR',
  SUBMIT_PAYPAL_PAYMENT_CANCEL = 'SUBMIT_PAYPAL_PAYMENT_CANCEL',
  SUBMIT_2C2P_PAYMENT = 'SUBMIT_2C2P_PAYMENT',
  REDIRECT_2C2P_PAYMENT = 'REDIRECT_2C2P_PAYMENT',
  SUBMIT_2C2P_PAYMENT_SUCCESS = 'SUBMIT_2C2P_PAYMENT_SUCCESS',
  SUBMIT_2C2P_PAYMENT_PENDING = 'SUBMIT_2C2P_PAYMENT_PENDING',
  SUBMIT_2C2P_PAYMENT_CANCELED = 'SUBMIT_2C2P_PAYMENT_CANCELED',
  SUBMIT_2C2P_PAYMENT_REJECTED = 'SUBMIT_2C2P_PAYMENT_REJECTED',
  SUBMIT_2C2P_PAYMENT_FAIL = 'SUBMIT_2C2P_PAYMENT_FAIL',
  SUBMIT_KBANK_PAYMENT = 'SUBMIT_KBANK_PAYMENT',
  SUBMIT_PAY_SOLUTION_PAYMENT = 'SUBMIT_PAY_SOLUTION_PAYMENT',
  GET_OMISE_ORDER_INFO = 'GET_OMISE_ORDER_INFO',
  SUBMIT_OMISE_PAYMENT = 'SUBMIT_OMISE_PAYMENT',
  SUBMIT_OMISE_PROMTPAY_PAYMENT = 'SUBMIT_OMISE_PROMTPAY_PAYMENT',
  SUBMIT_OMISE_CREDIT_CARD_PAYMENT = 'SUBMIT_OMISE_CREDIT_CARD_PAYMENT',
  SUBMIT_OMISE_INTERNET_BANKING = 'SUBMIT_OMISE_INTERNET_BANKING',
  INTERVAL_CHECK_PURCHASE_ORDER_STATUS = 'INTERVAL_CHECK_PURCHASE_ORDER_STATUS',
  CHECK_PURCHASE_ORDER_STATUS = 'CHECK_PURCHASE_ORDER_STATUS',
  SELECT_LOGISTIC_METHOD = 'SELECT_LOGISTIC_METHOD',
  CORRECT_ADDRESS = 'CORRECT_ADDRESS', // unused
  CORRECT_ADDRESS_COD = 'CORRECT_ADDRESS_COD', // unused
  IN_CORRECT_ADDRESS = 'IN_CORRECT_ADDRESS', // unused
  ADD_ADDRESS = 'ADD_ADDRESS', // unused
  EMPTY = 'EMPTY',
  ADD_ITEM_TO_CART_CATALOG = 'ADD_ITEM_TO_CART_CATALOG',
}

export enum EnumPurchaseOrderStatus {
  FOLLOW = 'FOLLOW',
  WAITING_FOR_PAYMENT = 'WAITING_FOR_PAYMENT',
  CONFIRM_PAYMENT = 'CONFIRM_PAYMENT',
  WAITING_FOR_SHIPMENT = 'WAITING_FOR_SHIPMENT',
  CLOSE_SALE = 'CLOSE_SALE',
  REJECT = 'REJECT',
  EXPIRED = 'EXPIRED',
  MARKET_PLACE_RETURNED = 'MARKET_PLACE_RETURNED',
  MARKET_PLACE_IN_CANCEL = 'MARKET_PLACE_IN_CANCEL',
  MARKET_PLACE_FAILED = 'MARKET_PLACE_FAILED',
  MARKET_PLACE_PROCESSED = 'MARKET_PLACE_PROCESSED',
  MARKET_PLACE_SHIPPED = 'MARKET_PLACE_SHIPPED',
  MARKET_PLACE_PENDING = 'MARKET_PLACE_PENDING',
}

export enum PaypalEnumHandler {
  APPROVED = 'APPROVED',
  ON_CANCEL = 'ON_CANCEL',
  ON_ERROR = 'ON_ERROR',
}

export enum PaypalPaymentIntent {
  CAPTURE = 'CAPTURE',
}
export enum PaypalPaymentStatus {
  APPROVED = 'APPROVED',
  COMPLETED = 'COMPLETED',
}
export enum UpdatePurchasePaymentMode {
  EDIT = 'EDIT',
  UPDATE = 'UPDATE',
}

export enum PrintingReportType {
  RECEIPT = 'receipt',
  VERTICAL_COD = 'vertical-cod',
  HORIZON_COD = 'horizon-cod',
  VERTICAL = 'vertical',
  HORIZON = 'horizon',
  RECEIPT_COD = 'receipt-cod',
  TELERIK = 'telerik',
  TELERIKANDFLASH = 'telerik,flash',
  FLASH_A4 = 'flash-a4',
  FLASH = 'flash-100', // 100 x 150
  // thaipost
  THAIPOST_DROP_OFF_A4 = 'thaipost-drop-off-a4',
  THAIPOST_DROP_OFF_100 = 'thaipost-drop-off-100',
  THAIPOST_BOOK_A4 = 'thaipost-book-a4',
  THAIPOST_BOOK_100 = 'thaipost-book-100',
  THAIPOST_MAUNAL_A4 = 'thaipost-maunal-a4',
  THAIPOST_MAUNAL_100 = 'thaipost-maunal-100',
  // j and  t
  J_T_COD_100 = 'jt-cod-100',
  J_T_COD_A4 = 'jt-cod-a4',
  J_T_DROP_OFF_A4 = 'jt-drop-off-a4',
  J_T_DROP_OFF_100 = 'jt-drop-off-100',
  J_T_MAUNAL_A4 = 'jt-maunal-a4',
  J_T_MAUNAL_100 = 'jt-maunal-100',
  // ALPHA
  ALPHA_DROP_OFF_A4 = 'alpha-drop-off-a4',
  ALPHA_MANUNAL_A4 = 'alpha-maunal-a4',
  // RECEIPT
  RECEIPT_A4 = 'receipt',
  RECEIPT_57 = 'receipt-57',
  RECEIPT_100 = 'receipt-100',
}
export enum SizeReport {
  SIZE_A4 = 'a4',
  SIZE_100x150mm = '100',
  SIZE_57mm = '57',
}
export enum TrackingTypeEnum {
  MANUAL = 'MANUAL',
  CUSTOM = 'CUSTOM',
  DROP_OFF = 'DROP_OFF',
  BOOK = 'BOOK',
}
export const isFlashReport = true;
export const isNotFlashReport = false;
export enum ReportTypeSelected {
  ISMANUAL_A4 = 'ISMANUAL_A4',
  ISMANUAL_100X150 = 'ISMANUAL_100X150',
  ISBOOK_A4 = 'ISBOOK_A4',
  ISBOOK_100X150 = 'ISBOOK_100X150',
  ISCOD_A4 = 'ISCOD_A4',
  ISCOD_100X150 = 'ISCOD_100X150',
  ISDROPOFF_A4 = 'ISDROPOFF_A4',
  ISDROPOFF_100X150 = 'ISDROPOFF_100X150',
}

export enum ReportType {
  RECEIPT = 'receipt',
  LABEL = 'label',
}
export enum DeliveryType {
  FLASH = 'FLASH_EXPRESS',
  JANDT = 'J&T Express',
  JANDT_PURCHASE_ORDER = 'J_AND_T',
  THAIPOST = 'THAILAND_POST',
  THAIPOST_EMS = 'EMS_THAILAND',
}
export enum reportNameDelivery {
  THAIPOST = 'thaipost',
  JANDT = 'jt',
  FLASH = 'flash',
}
export enum reportTrackingType {
  BOOK = 'book',
  DROPOFF = 'drop-off',
  MAUNAL = 'maunal',
  COD = 'cod',
}

export enum EnumPurchaseOrderSubStatus {
  // PIPELINE_STEP_MISMATCH = 'PIPELINE_STEP_MISMATCH',
  // UPDATE_STEP_FAILED = 'UPDATE_STEP_FAILED',
  TRANSACTION_2C2P_FAILED = 'TRANSACTION_2C2P_FAILED', // Incase failed
  //
  PAYMENT_2C2P_FAILED = 'PAYMENT_2C2P_FAILED', // Incase to have been refunds
  PAYMENT_OMISE_FAILED = 'PAYMENT_OMISE_FAILED', // Incase to have been refunds
  PAYMENT_PAYPAL_FAILED = 'PAYMENT_PAYPAL_FAILED', // Incase to have been refunds
  // PRODUCT_RESERVED_FAILED = 'PRODUCT_RESERVED_FAILED',
  PRODUCT_SUBTRACT_FAILED = 'PRODUCT_SUBTRACT_FAILED',
  PURCHASE_ORDER_REFUND_FAILED = 'PURCHASE_ORDER_REFUND_FAILED',
  // INSUFFICIENT_PRODUCT_RESERVED = 'INSUFFICIENT_PRODUCT_RESERVED',
  // INSUFFICIENT_PRODUCT_SUBTRACT = 'INSUFFICIENT_PRODUCT_SUBTRACT',
  REFUND_PAYPAL_FAILED = 'REFUND_PAYPAL_FAILED',
  REFUND_2C2P_FAILED = 'REFUND_2C2P_FAILED',
  REFUND_OMISE_CREDIT_FAILED = 'REFUND_OMISE_CREDIT_FAILED',
  // REFUND_OMISE_PROMPTPAY_FAILED = 'REFUND_OMISE_PROMPTPAY_FAILED',
  // REFUND_OMISE_INTERNET_BANKING_FAILED = 'REFUND_OMISE_INTERNET_BANKING_FAILED',
  // SUBTRACT_PRODUCT_AND_REFUND_OMISE_PROMPTPAY_FAILED = 'SUBTRACT_AND_REFUND_OMISE_PROMPTPAY_FAILED',
  // SUBTRACT_PRODUCT_AND_REFUND_OMISE_INTERNET_BANKING_FAILED = 'SUBTRACT_AND_REFUND_OMISE_INTERNET_BANKING_FAILED',
  // GENERATE_TRACKING_FAILED = 'GENERATE_TRACKING_FAILED',
  // GENERATE_THAIPOST_DROPOFF_FAILED = 'GENERATE_THAIPOST_DROPOFF_FAILED',
  // GENERATE_THAIPOST_BOOKING_FAILED = 'GENERATE_THAIPOST_BOOKING_FAILED',
  // GENERATE_FLASH_DROPOFF_FAILED = 'GENERATE_FLASH_DROPOFF_FAILED',
  // GENERATE_JTEXPRESS_BOOKING_FAILED = 'GENERATE_JTEXPRESS_BOOKING_FAILED',
  // GENERATE_ALPHA_DROPOFF_FAILED = 'GENERATE_ALPHA_DROPOFF_FAILED',
  // GENERATE_NINJAVAN_DROPOFF_FAILED = 'GENERATE_NINJAVAN_DROPOFF_FAILED',
}

export enum PaypalPaymentLinksRelEnum {
  self = 'self',
  update = 'update',
  capture = 'capture',
}
