import {
  EBackgroundSize,
  EBullet,
  EDecoration,
  EFontFamilyCode,
  EFontStyle,
  ElinkType,
  ENumberPosition,
  EnumThemeRenderingSettingColorType,
  EnumThemeRenderingSettingFontType,
  ETextAlignment,
  fontSizeEm,
  fontSizePx,
  HoverAnimationTypes,
  OpenWindowTypes,
  ShoppingCartPatternPaginationTypes,
  ShoppingCartProductBuyButtonIconTypes,
  ShoppingCartProductBuyButtonStyleTypes,
  ShoppingCartProductBuyFavButtonStyleTypes,
  ShoppingCartProductCodeSkuStyleTypes,
  ShoppingCartProductLabelBestStyleTypes,
  ShoppingCartProductLabelNewStyleTypes,
  ShoppingCartProductLabelRecommendedStyleTypes,
  ShoppingCartProductLayoutTypes,
  ShoppingCartProductNameTypes,
  ShoppingCartProductPriceStyleTypes,
  ShoppingCartProductRatingStyleTypes,
  textOpacity,
  UnitEnum,
} from '@reactor-room/cms-models-lib';

export const textDefaultValue = {
  defaultFontFamilyCode: EFontFamilyCode.PROMPT,
  defaultFontFamilyStyle: EFontStyle.REGULAR,
  defaultFontSizePx: fontSizePx[5],
  defaultFontSizeEm: fontSizeEm[9],
  defaultTextLightColor: '#000000',
  defaultTextDarkColor: '#ffffff',
  defaultTextOpacity: textOpacity[textOpacity.length - 1],
  defaultTextAlignment: ETextAlignment.LEFT,
  defaultPaginationStyle: ShoppingCartPatternPaginationTypes.PAGINATION_1,
  defaultParagraphSetting: 'normal',
  defaultTextDecoration: EDecoration.DASH,
  defaultTextThemeStyle: EnumThemeRenderingSettingFontType.NONE,
  defaultTextThemeColor: EnumThemeRenderingSettingColorType.NONE,
  defaultFontSizeUnit: UnitEnum.PX,
  defaultTextNumberPosition: ENumberPosition.SCRIPT,
  defaultTextBullet: EBullet.NONE,
  defaultTextLinkType: ElinkType.URL,
  defaultOpenWindowType: OpenWindowTypes.CURRENT,
  defaultImageScale: EBackgroundSize.UNSET,
  defaultHoverAnimation: HoverAnimationTypes.NONE,
  defaultProductSKUStyle: ShoppingCartProductCodeSkuStyleTypes.STYLE_1,
  defaultLayoutImage: ShoppingCartProductLayoutTypes.OUTSIDE_IMAGE,
  defaultProductNameType: ShoppingCartProductNameTypes.FULL_NAME,
  defaultProductRatingStyle: ShoppingCartProductRatingStyleTypes.STYLE_1,
  defaultProductPriceStyle: ShoppingCartProductPriceStyleTypes.STYLE_1,
  defaultColorPercent: '100%',
  defaultProductBuyButtonStyle: ShoppingCartProductBuyButtonStyleTypes.STYLE_1,
  defaultProductBuyButtonIcon: ShoppingCartProductBuyButtonIconTypes.STYLE_1,
  defaultProductFavButtonIcon: ShoppingCartProductBuyFavButtonStyleTypes.STYLE_1,
  defaultProductLabelNewStyle: ShoppingCartProductLabelNewStyleTypes.STYLE_1,
  defaultProductLabelBestStyle: ShoppingCartProductLabelBestStyleTypes.STYLE_1,
  defaultProductLabelRecommendedStyle: ShoppingCartProductLabelRecommendedStyleTypes.STYLE_1,
};
