import { IRenderingComponentData } from '@reactor-room/cms-models-lib';
import { environmentLib } from '@reactor-room/environment-services-frontend';
import { changePathUrlToFullUrl } from './component.domain';

const fileServer = environmentLib.filesServer;
const subscriptionID = '8ce4d20f-d980-4127-8560-9523650d5f72';
describe('changePathUrlToFullUrl', () => {
  test('changePathUrlToFullUrl test1', () => {
    const components = [
      {
        isActive: true,
        _id: '61ea96428433226badf8856d',
        componentType: 'cms-next-cms-media-gallery-rendering',
        commonSettings: {
          border: {
            corner: {
              topLeft: 0,
              topRight: 0,
              bottomLeft: 0,
              bottomRight: 0,
            },
            color: '',
            opacity: 100,
            thickness: 0,
            position: {
              left: false,
              top: false,
              right: false,
              bottom: false,
            },
          },
          shadow: {
            isShadow: false,
            color: '',
            opacity: 100,
            xAxis: 0,
            yAxis: 0,
            distance: 0,
            blur: 0,
          },
          hover: {
            style: '',
            textHover: '',
          },
          effect: null,
          background: {
            currentStyle: 'COLOR',
            layoutSettingBackgroundColorForm: {
              color: '',
              opacity: 100,
            },
            layoutSettingBackgroundImageForm: {
              imgUrl: '',
              position: 'center center',
              imageScale: 'unset',
              opacity: 100,
              colorOverlay: '',
              colorOverlayOpacity: 100,
              width: null,
              height: null,
              repeat: false,
            },
            layoutSettingBackgroundVideoForm: {
              videoUrl: '',
              position: 'center center',
              playInLoop: false,
              videoSpeed: 1,
              videoScale: 'unset',
              opacity: 100,
              colorOverlay: '',
              colorOverlayOpacity: 100,
              width: null,
              height: null,
            },
          },
          advance: {
            margin: {
              left: 0,
              top: 0,
              right: 0,
              bottom: 0,
            },
            padding: {
              left: 20,
              top: 20,
              right: 20,
              bottom: 20,
            },
            horizontalPosition: 'flex-start',
            verticalPosition: 'flex-start',
          },
          customize: {
            cssStyle: '#element-1642763135843{}',
            elementId: 'element-1642763135843',
          },
        },
        options: {
          gallery: {
            galleryPatternId: 'GALLERY_1',
            galleryPatternUrl: 'assets/cms/media-style/gallery/gallery-1.png',
            galleryGap: 0,
            gallleryList: [],
            galleryMaxHeight: 250,
            isChangePattern: null,
          },
          control: {
            isPageSlide: false,
            isAutoSlide: false,
            isPageButton: false,
            pageButtonSize: 30,
            pageButtonOffset: 0,
            isPageArrow: false,
            pageArrowSize: 30,
            pageArrowOffset: 0,
            slideSpeed: 1000,
          },
        },
        layoutID: null,
        layoutPosition: null,
        nextId: '61f01c49fafcc80a686ccc43',
      },
    ] as IRenderingComponentData[];
    const fullUrl = changePathUrlToFullUrl(components, fileServer, subscriptionID);
    const expectResult = [
      {
        isActive: true,
        _id: '61ea96428433226badf8856d',
        componentType: 'cms-next-cms-media-gallery-rendering',
        commonSettings: {
          border: {
            corner: {
              topLeft: 0,
              topRight: 0,
              bottomLeft: 0,
              bottomRight: 0,
            },
            color: '',
            opacity: 100,
            thickness: 0,
            position: {
              left: false,
              top: false,
              right: false,
              bottom: false,
            },
          },
          shadow: {
            isShadow: false,
            color: '',
            opacity: 100,
            xAxis: 0,
            yAxis: 0,
            distance: 0,
            blur: 0,
          },
          hover: {
            style: '',
            textHover: '',
          },
          effect: null,
          background: {
            currentStyle: 'COLOR',
            layoutSettingBackgroundColorForm: {
              color: '',
              opacity: 100,
            },
            layoutSettingBackgroundImageForm: {
              imgUrl: '',
              position: 'center center',
              imageScale: 'unset',
              opacity: 100,
              colorOverlay: '',
              colorOverlayOpacity: 100,
              width: null,
              height: null,
              repeat: false,
            },
            layoutSettingBackgroundVideoForm: {
              videoUrl: '',
              position: 'center center',
              playInLoop: false,
              videoSpeed: 1,
              videoScale: 'unset',
              opacity: 100,
              colorOverlay: '',
              colorOverlayOpacity: 100,
              width: null,
              height: null,
            },
          },
          advance: {
            margin: {
              left: 0,
              top: 0,
              right: 0,
              bottom: 0,
            },
            padding: {
              left: 20,
              top: 20,
              right: 20,
              bottom: 20,
            },
            horizontalPosition: 'flex-start',
            verticalPosition: 'flex-start',
          },
          customize: {
            cssStyle: '#element-1642763135843{}',
            elementId: 'element-1642763135843',
          },
        },
        options: {
          gallery: {
            galleryPatternId: 'GALLERY_1',
            galleryPatternUrl: 'assets/cms/media-style/gallery/gallery-1.png',
            galleryGap: 0,
            gallleryList: [],
            galleryMaxHeight: 250,
            isChangePattern: null,
          },
          control: {
            isPageSlide: false,
            isAutoSlide: false,
            isPageButton: false,
            pageButtonSize: 30,
            pageButtonOffset: 0,
            isPageArrow: false,
            pageArrowSize: 30,
            pageArrowOffset: 0,
            slideSpeed: 1000,
          },
        },
        layoutID: null,
        layoutPosition: null,
        nextId: '61f01c49fafcc80a686ccc43',
      },
    ] as IRenderingComponentData[];
    expect(fullUrl).toStrictEqual(expectResult);
  });
  test('changePathUrlToFullUrl test2', () => {
    const components = [
      {
        isActive: true,
        _id: '62134dbc1224d760ad7b1a07',
        componentType: 'cms-next-cms-media-gallery-rendering',
        commonSettings: {
          border: {
            corner: {
              topLeft: 0,
              topRight: 0,
              bottomLeft: 0,
              bottomRight: 0,
            },
            color: '',
            opacity: 100,
            thickness: 0,
            position: {
              left: false,
              top: false,
              right: false,
              bottom: false,
            },
          },
          shadow: {
            isShadow: false,
            color: '',
            opacity: 100,
            xAxis: 0,
            yAxis: 0,
            distance: 0,
            blur: 0,
          },
          hover: {
            style: '',
            textHover: '',
          },
          effect: null,
          background: {
            currentStyle: 'COLOR',
            layoutSettingBackgroundColorForm: {
              color: '',
              opacity: 100,
            },
            layoutSettingBackgroundImageForm: {
              imgUrl: '',
              position: 'center center',
              imageScale: 'unset',
              opacity: 100,
              colorOverlay: '',
              colorOverlayOpacity: 100,
              width: null,
              height: null,
              repeat: false,
            },
            layoutSettingBackgroundVideoForm: {
              videoUrl: '',
              position: 'center center',
              playInLoop: false,
              videoSpeed: 1,
              videoScale: 'unset',
              opacity: 100,
              colorOverlay: '',
              colorOverlayOpacity: 100,
              width: null,
              height: null,
            },
          },
          advance: {
            margin: {
              left: 0,
              top: 0,
              right: 0,
              bottom: 0,
            },
            padding: {
              left: 20,
              top: 20,
              right: 20,
              bottom: 20,
            },
            horizontalPosition: 'flex-start',
            verticalPosition: 'flex-start',
          },
          customize: {
            cssStyle: '#element-1645432251120{}',
            elementId: '62134dbc1224d760ad7b1a07',
          },
        },
        options: {
          gallery: {
            galleryPatternId: 'GALLERY_4',
            galleryPatternUrl: 'assets/cms/media-style/gallery/gallery-4.png',
            galleryGap: 0,
            gallleryList: [
              {
                url: 'system/d6a243a3-c326-4cce-b0d7-dfaa17866eb2/products/1243/%E0%B9%84%E0%B8%97%E0%B8%A2%E0%B8%A3%E0%B8%B9%E0%B8%9Bxxxxxxxxxx=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx32mz1265276805283.jpg',
                fileType: 'IMAGE',
                title: 'ไทยรูปxxxxxxxxxx?=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                setting: {
                  generalBackgroundSetting: {
                    currentStyle: 'IMAGE',
                    layoutSettingBackgroundColorForm: {
                      color: '',
                      opacity: 100,
                    },
                    layoutSettingBackgroundImageForm: {
                      imgUrl:
                        'system/d6a243a3-c326-4cce-b0d7-dfaa17866eb2/products/1243/%E0%B9%84%E0%B8%97%E0%B8%A2%E0%B8%A3%E0%B8%B9%E0%B8%9Bxxxxxxxxxx=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx32mz1265276805283.jpg',
                      position: 'center center',
                      imageScale: 'cover',
                      opacity: 100,
                      colorOverlay: '',
                      colorOverlayOpacity: 100,
                      width: null,
                      height: null,
                      repeat: false,
                    },
                    layoutSettingBackgroundVideoForm: {
                      videoUrl: '',
                      position: 'center center',
                      playInLoop: false,
                      videoSpeed: 1,
                      videoScale: 'cover',
                      opacity: 100,
                      colorOverlay: '',
                      colorOverlayOpacity: 100,
                      width: null,
                      height: null,
                    },
                  },
                  generalLinkSetting: {
                    linkType: 'link-to-url',
                    linkValue: null,
                    parentID: null,
                  },
                  generalTextSetting: {
                    text: {
                      isText: true,
                      text: [
                        {
                          cultureUI: 'TH',
                          title: 'ไทยรูปxxxxxxxxxx?=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                          description: 'Description',
                        },
                      ],
                      isFontDefault: false,
                      isFontIndexDefault: 0,
                      isStyleDefault: false,
                      isTextColorDefault: false,
                      isTextOpacityDefault: false,
                      isLineHeightDefault: false,
                      isLetterSpacingDefault: false,
                      fontFamily: 'prompt',
                      fontStyle: 'Regular',
                      titleFontSize: '18px',
                      descriptionFontSize: '14px',
                      textColor: '#616161',
                      textOpacity: '1',
                      textAlignment: '',
                      lineHeight: 'normal',
                      letterSpacing: 'normal',
                      textAnimation: '',
                    },
                    overlay: {
                      isOverlay: true,
                      isOverlayFullWidth: false,
                      overlayColor: '#ffffff',
                      overlayOpacity: '0.3',
                      overlayAnimation: '',
                    },
                    horizontalPosition: 'flex-start',
                    verticalPosition: 'flex-start',
                    isApplyAll: false,
                  },
                },
              },
              {
                url: 'system/d6a243a3-c326-4cce-b0d7-dfaa17866eb2/products/1244/production_4fab6ccf-45ca-4408-bc90-0a5d2f44c2e0_cartoon-animal-pillow-and-blanket_4fab6ccf-45ca-4408-bc90-0a5d2f44c2e0_584_16424816418652xaaz1435891542451.jpg',
                fileType: 'IMAGE',
                title: 'production_4fab6ccf-45ca-4408-bc90-0a5d2f44c2e0_Cartoon-Animal-Pillow-And-Blanket_4fab6ccf-45ca-4408-bc90-0a5d2f44c2e0_584_1642481641865 (2)',
                setting: {
                  generalBackgroundSetting: {
                    currentStyle: 'IMAGE',
                    layoutSettingBackgroundColorForm: {
                      color: '',
                      opacity: 100,
                    },
                    layoutSettingBackgroundImageForm: {
                      imgUrl:
                        'system/d6a243a3-c326-4cce-b0d7-dfaa17866eb2/products/1244/production_4fab6ccf-45ca-4408-bc90-0a5d2f44c2e0_cartoon-animal-pillow-and-blanket_4fab6ccf-45ca-4408-bc90-0a5d2f44c2e0_584_16424816418652xaaz1435891542451.jpg',
                      position: 'center center',
                      imageScale: 'cover',
                      opacity: 100,
                      colorOverlay: '',
                      colorOverlayOpacity: 100,
                      width: null,
                      height: null,
                      repeat: false,
                    },
                    layoutSettingBackgroundVideoForm: {
                      videoUrl: '',
                      position: 'center center',
                      playInLoop: false,
                      videoSpeed: 1,
                      videoScale: 'cover',
                      opacity: 100,
                      colorOverlay: '',
                      colorOverlayOpacity: 100,
                      width: null,
                      height: null,
                    },
                  },
                  generalLinkSetting: {
                    linkType: 'link-to-url',
                    linkValue: null,
                    parentID: null,
                  },
                  generalTextSetting: {
                    text: {
                      isText: true,
                      text: [
                        {
                          cultureUI: 'TH',
                          title: 'production_4fab6ccf-45ca-4408-bc90-0a5d2f44c2e0_Cartoon-Animal-Pillow-And-Blanket_4fab6ccf-45ca-4408-bc90-0a5d2f44c2e0_584_1642481641865 (2)',
                          description: 'Description',
                        },
                      ],
                      isFontDefault: false,
                      isFontIndexDefault: 0,
                      isStyleDefault: false,
                      isTextColorDefault: false,
                      isTextOpacityDefault: false,
                      isLineHeightDefault: false,
                      isLetterSpacingDefault: false,
                      fontFamily: 'prompt',
                      fontStyle: 'Regular',
                      titleFontSize: '18px',
                      descriptionFontSize: '14px',
                      textColor: '#616161',
                      textOpacity: '1',
                      textAlignment: '',
                      lineHeight: 'normal',
                      letterSpacing: 'normal',
                      textAnimation: '',
                    },
                    overlay: {
                      isOverlay: true,
                      isOverlayFullWidth: false,
                      overlayColor: '#ffffff',
                      overlayOpacity: '0.3',
                      overlayAnimation: '',
                    },
                    horizontalPosition: 'flex-start',
                    verticalPosition: 'flex-start',
                    isApplyAll: false,
                  },
                },
              },
              {
                url: 'system/d6a243a3-c326-4cce-b0d7-dfaa17866eb2/products/1246/img-0086jpgcz0n1461167233851.jpg',
                fileType: 'IMAGE',
                title: 'IMG-0086.JPG',
                setting: {
                  generalBackgroundSetting: {
                    currentStyle: 'IMAGE',
                    layoutSettingBackgroundColorForm: {
                      color: '',
                      opacity: 100,
                    },
                    layoutSettingBackgroundImageForm: {
                      imgUrl: 'system/d6a243a3-c326-4cce-b0d7-dfaa17866eb2/products/1246/img-0086jpgcz0n1461167233851.jpg',
                      position: 'center center',
                      imageScale: 'cover',
                      opacity: 100,
                      colorOverlay: '',
                      colorOverlayOpacity: 100,
                      width: null,
                      height: null,
                      repeat: false,
                    },
                    layoutSettingBackgroundVideoForm: {
                      videoUrl: '',
                      position: 'center center',
                      playInLoop: false,
                      videoSpeed: 1,
                      videoScale: 'cover',
                      opacity: 100,
                      colorOverlay: '',
                      colorOverlayOpacity: 100,
                      width: null,
                      height: null,
                    },
                  },
                  generalLinkSetting: {
                    linkType: 'link-to-url',
                    linkValue: null,
                    parentID: null,
                  },
                  generalTextSetting: {
                    text: {
                      isText: true,
                      text: [
                        {
                          cultureUI: 'TH',
                          title: 'IMG-0086.JPG',
                          description: 'Description',
                        },
                      ],
                      isFontDefault: false,
                      isFontIndexDefault: 0,
                      isStyleDefault: false,
                      isTextColorDefault: false,
                      isTextOpacityDefault: false,
                      isLineHeightDefault: false,
                      isLetterSpacingDefault: false,
                      fontFamily: 'prompt',
                      fontStyle: 'Regular',
                      titleFontSize: '18px',
                      descriptionFontSize: '14px',
                      textColor: '#616161',
                      textOpacity: '1',
                      textAlignment: '',
                      lineHeight: 'normal',
                      letterSpacing: 'normal',
                      textAnimation: '',
                    },
                    overlay: {
                      isOverlay: true,
                      isOverlayFullWidth: false,
                      overlayColor: '#ffffff',
                      overlayOpacity: '0.3',
                      overlayAnimation: '',
                    },
                    horizontalPosition: 'flex-start',
                    verticalPosition: 'flex-start',
                    isApplyAll: false,
                  },
                },
              },
            ],
            galleryMaxHeight: 500,
            isChangePattern: true,
          },
          control: {
            isPageSlide: false,
            isAutoSlide: false,
            isPageButton: false,
            pageButtonSize: 30,
            pageButtonOffset: 0,
            isPageArrow: false,
            pageArrowSize: 30,
            pageArrowOffset: 0,
            slideSpeed: 1000,
          },
        },
        layoutID: null,
        layoutPosition: null,
        nextId: null,
      },
    ] as IRenderingComponentData[];
    const fullUrl = changePathUrlToFullUrl(components, fileServer, subscriptionID);
    const expectResult = [
      {
        isActive: true,
        _id: '62134dbc1224d760ad7b1a07',
        componentType: 'cms-next-cms-media-gallery-rendering',
        commonSettings: {
          border: {
            corner: {
              topLeft: 0,
              topRight: 0,
              bottomLeft: 0,
              bottomRight: 0,
            },
            color: '',
            opacity: 100,
            thickness: 0,
            position: {
              left: false,
              top: false,
              right: false,
              bottom: false,
            },
          },
          shadow: {
            isShadow: false,
            color: '',
            opacity: 100,
            xAxis: 0,
            yAxis: 0,
            distance: 0,
            blur: 0,
          },
          hover: {
            style: '',
            textHover: '',
          },
          effect: null,
          background: {
            currentStyle: 'COLOR',
            layoutSettingBackgroundColorForm: {
              color: '',
              opacity: 100,
            },
            layoutSettingBackgroundImageForm: {
              imgUrl: '',
              position: 'center center',
              imageScale: 'unset',
              opacity: 100,
              colorOverlay: '',
              colorOverlayOpacity: 100,
              width: null,
              height: null,
              repeat: false,
            },
            layoutSettingBackgroundVideoForm: {
              videoUrl: '',
              position: 'center center',
              playInLoop: false,
              videoSpeed: 1,
              videoScale: 'unset',
              opacity: 100,
              colorOverlay: '',
              colorOverlayOpacity: 100,
              width: null,
              height: null,
            },
          },
          advance: {
            margin: {
              left: 0,
              top: 0,
              right: 0,
              bottom: 0,
            },
            padding: {
              left: 20,
              top: 20,
              right: 20,
              bottom: 20,
            },
            horizontalPosition: 'flex-start',
            verticalPosition: 'flex-start',
          },
          customize: {
            cssStyle: '#element-1645432251120{}',
            elementId: '62134dbc1224d760ad7b1a07',
          },
        },
        options: {
          gallery: {
            galleryPatternId: 'GALLERY_4',
            galleryPatternUrl: 'assets/cms/media-style/gallery/gallery-4.png',
            galleryGap: 0,
            gallleryList: [
              {
                url: 'http://localhost:3000/8ce4d20f-d980-4127-8560-9523650d5f72/system/d6a243a3-c326-4cce-b0d7-dfaa17866eb2/products/1243/%E0%B9%84%E0%B8%97%E0%B8%A2%E0%B8%A3%E0%B8%B9%E0%B8%9Bxxxxxxxxxx=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx32mz1265276805283.jpg',
                fileType: 'IMAGE',
                title: 'ไทยรูปxxxxxxxxxx?=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                setting: {
                  generalBackgroundSetting: {
                    currentStyle: 'IMAGE',
                    layoutSettingBackgroundColorForm: {
                      color: '',
                      opacity: 100,
                    },
                    layoutSettingBackgroundImageForm: {
                      imgUrl:
                        'http://localhost:3000/8ce4d20f-d980-4127-8560-9523650d5f72/system/d6a243a3-c326-4cce-b0d7-dfaa17866eb2/products/1243/%E0%B9%84%E0%B8%97%E0%B8%A2%E0%B8%A3%E0%B8%B9%E0%B8%9Bxxxxxxxxxx=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx32mz1265276805283.jpg',
                      position: 'center center',
                      imageScale: 'cover',
                      opacity: 100,
                      colorOverlay: '',
                      colorOverlayOpacity: 100,
                      width: null,
                      height: null,
                      repeat: false,
                    },
                    layoutSettingBackgroundVideoForm: {
                      videoUrl: '',
                      position: 'center center',
                      playInLoop: false,
                      videoSpeed: 1,
                      videoScale: 'cover',
                      opacity: 100,
                      colorOverlay: '',
                      colorOverlayOpacity: 100,
                      width: null,
                      height: null,
                    },
                  },
                  generalLinkSetting: {
                    linkType: 'link-to-url',
                    linkValue: null,
                    parentID: null,
                  },
                  generalTextSetting: {
                    text: {
                      isText: true,
                      text: [
                        {
                          cultureUI: 'TH',
                          title: 'ไทยรูปxxxxxxxxxx?=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                          description: 'Description',
                        },
                      ],
                      isFontDefault: false,
                      isFontIndexDefault: 0,
                      isStyleDefault: false,
                      isTextColorDefault: false,
                      isTextOpacityDefault: false,
                      isLineHeightDefault: false,
                      isLetterSpacingDefault: false,
                      fontFamily: 'prompt',
                      fontStyle: 'Regular',
                      titleFontSize: '18px',
                      descriptionFontSize: '14px',
                      textColor: '#616161',
                      textOpacity: '1',
                      textAlignment: '',
                      lineHeight: 'normal',
                      letterSpacing: 'normal',
                      textAnimation: '',
                    },
                    overlay: {
                      isOverlay: true,
                      isOverlayFullWidth: false,
                      overlayColor: '#ffffff',
                      overlayOpacity: '0.3',
                      overlayAnimation: '',
                    },
                    horizontalPosition: 'flex-start',
                    verticalPosition: 'flex-start',
                    isApplyAll: false,
                  },
                },
              },
              {
                url: 'http://localhost:3000/8ce4d20f-d980-4127-8560-9523650d5f72/system/d6a243a3-c326-4cce-b0d7-dfaa17866eb2/products/1244/production_4fab6ccf-45ca-4408-bc90-0a5d2f44c2e0_cartoon-animal-pillow-and-blanket_4fab6ccf-45ca-4408-bc90-0a5d2f44c2e0_584_16424816418652xaaz1435891542451.jpg',
                fileType: 'IMAGE',
                title: 'production_4fab6ccf-45ca-4408-bc90-0a5d2f44c2e0_Cartoon-Animal-Pillow-And-Blanket_4fab6ccf-45ca-4408-bc90-0a5d2f44c2e0_584_1642481641865 (2)',
                setting: {
                  generalBackgroundSetting: {
                    currentStyle: 'IMAGE',
                    layoutSettingBackgroundColorForm: {
                      color: '',
                      opacity: 100,
                    },
                    layoutSettingBackgroundImageForm: {
                      imgUrl:
                        'http://localhost:3000/8ce4d20f-d980-4127-8560-9523650d5f72/system/d6a243a3-c326-4cce-b0d7-dfaa17866eb2/products/1244/production_4fab6ccf-45ca-4408-bc90-0a5d2f44c2e0_cartoon-animal-pillow-and-blanket_4fab6ccf-45ca-4408-bc90-0a5d2f44c2e0_584_16424816418652xaaz1435891542451.jpg',
                      position: 'center center',
                      imageScale: 'cover',
                      opacity: 100,
                      colorOverlay: '',
                      colorOverlayOpacity: 100,
                      width: null,
                      height: null,
                      repeat: false,
                    },
                    layoutSettingBackgroundVideoForm: {
                      videoUrl: '',
                      position: 'center center',
                      playInLoop: false,
                      videoSpeed: 1,
                      videoScale: 'cover',
                      opacity: 100,
                      colorOverlay: '',
                      colorOverlayOpacity: 100,
                      width: null,
                      height: null,
                    },
                  },
                  generalLinkSetting: {
                    linkType: 'link-to-url',
                    linkValue: null,
                    parentID: null,
                  },
                  generalTextSetting: {
                    text: {
                      isText: true,
                      text: [
                        {
                          cultureUI: 'TH',
                          title: 'production_4fab6ccf-45ca-4408-bc90-0a5d2f44c2e0_Cartoon-Animal-Pillow-And-Blanket_4fab6ccf-45ca-4408-bc90-0a5d2f44c2e0_584_1642481641865 (2)',
                          description: 'Description',
                        },
                      ],
                      isFontDefault: false,
                      isFontIndexDefault: 0,
                      isStyleDefault: false,
                      isTextColorDefault: false,
                      isTextOpacityDefault: false,
                      isLineHeightDefault: false,
                      isLetterSpacingDefault: false,
                      fontFamily: 'prompt',
                      fontStyle: 'Regular',
                      titleFontSize: '18px',
                      descriptionFontSize: '14px',
                      textColor: '#616161',
                      textOpacity: '1',
                      textAlignment: '',
                      lineHeight: 'normal',
                      letterSpacing: 'normal',
                      textAnimation: '',
                    },
                    overlay: {
                      isOverlay: true,
                      isOverlayFullWidth: false,
                      overlayColor: '#ffffff',
                      overlayOpacity: '0.3',
                      overlayAnimation: '',
                    },
                    horizontalPosition: 'flex-start',
                    verticalPosition: 'flex-start',
                    isApplyAll: false,
                  },
                },
              },
              {
                url: 'http://localhost:3000/8ce4d20f-d980-4127-8560-9523650d5f72/system/d6a243a3-c326-4cce-b0d7-dfaa17866eb2/products/1246/img-0086jpgcz0n1461167233851.jpg',
                fileType: 'IMAGE',
                title: 'IMG-0086.JPG',
                setting: {
                  generalBackgroundSetting: {
                    currentStyle: 'IMAGE',
                    layoutSettingBackgroundColorForm: {
                      color: '',
                      opacity: 100,
                    },
                    layoutSettingBackgroundImageForm: {
                      imgUrl:
                        'http://localhost:3000/8ce4d20f-d980-4127-8560-9523650d5f72/system/d6a243a3-c326-4cce-b0d7-dfaa17866eb2/products/1246/img-0086jpgcz0n1461167233851.jpg',
                      position: 'center center',
                      imageScale: 'cover',
                      opacity: 100,
                      colorOverlay: '',
                      colorOverlayOpacity: 100,
                      width: null,
                      height: null,
                      repeat: false,
                    },
                    layoutSettingBackgroundVideoForm: {
                      videoUrl: '',
                      position: 'center center',
                      playInLoop: false,
                      videoSpeed: 1,
                      videoScale: 'cover',
                      opacity: 100,
                      colorOverlay: '',
                      colorOverlayOpacity: 100,
                      width: null,
                      height: null,
                    },
                  },
                  generalLinkSetting: {
                    linkType: 'link-to-url',
                    linkValue: null,
                    parentID: null,
                  },
                  generalTextSetting: {
                    text: {
                      isText: true,
                      text: [
                        {
                          cultureUI: 'TH',
                          title: 'IMG-0086.JPG',
                          description: 'Description',
                        },
                      ],
                      isFontDefault: false,
                      isFontIndexDefault: 0,
                      isStyleDefault: false,
                      isTextColorDefault: false,
                      isTextOpacityDefault: false,
                      isLineHeightDefault: false,
                      isLetterSpacingDefault: false,
                      fontFamily: 'prompt',
                      fontStyle: 'Regular',
                      titleFontSize: '18px',
                      descriptionFontSize: '14px',
                      textColor: '#616161',
                      textOpacity: '1',
                      textAlignment: '',
                      lineHeight: 'normal',
                      letterSpacing: 'normal',
                      textAnimation: '',
                    },
                    overlay: {
                      isOverlay: true,
                      isOverlayFullWidth: false,
                      overlayColor: '#ffffff',
                      overlayOpacity: '0.3',
                      overlayAnimation: '',
                    },
                    horizontalPosition: 'flex-start',
                    verticalPosition: 'flex-start',
                    isApplyAll: false,
                  },
                },
              },
            ],
            galleryMaxHeight: 500,
            isChangePattern: true,
          },
          control: {
            isPageSlide: false,
            isAutoSlide: false,
            isPageButton: false,
            pageButtonSize: 30,
            pageButtonOffset: 0,
            isPageArrow: false,
            pageArrowSize: 30,
            pageArrowOffset: 0,
            slideSpeed: 1000,
          },
        },
        layoutID: null,
        layoutPosition: null,
        nextId: null,
      },
    ] as IRenderingComponentData[];
    expect(fullUrl).toStrictEqual(expectResult);
  });
});
