export const EnumJAndTExpressReasonResponseCode = {
  '1': 'success',
  '0': 'internal server error',
  S01: 'ogistics_interface data does not conform to JSON format standards',
  S02: 'The data_digest signature is incorrect and has not passed the checksum.',
  S03: 'The eccompanyid is incorrect and has not passed the checksum.',
  S04: 'The value of the service type msg_type is not in the scope specified by the document.',
  S05: 'The content format in logistics_interface is incorrect',
  S06: 'If the response is not received within 30 seconds when the order is created, it is considered to be timeout.',
  S07: 'The system is abnormal, please try again',
  S08: 'Eccompanyid error. Illegal e-commerce platform',
  S09: 'Freight query, shipment tracking query returns when there is no record',
  S10: 'Duplicate order number. Online order interface txlogisticid Duplicate order number',
  S11: 'Online order interface mailno repeating waybill number',
  S12: 'Order status is GOT can not cancel order',
  S13: 'Customer information does not exist',
  S15: 'Online order interface txlogisticid Order does not exist',
  S16: 'Online order interface mailno The waybill no does not exist',
  S17: 'Connect to the database or process execution exception',
  S18: 'The customer number does not exist in the shop table',
};
