export enum SocialTypes {
  FACEBOOK = 'facebook',
  LINE = 'line',
  LAZADA = 'lazada',
  SHOPEE = 'shopee',
  MORE_COMMERCE = 'more_commerce',
}

export enum EnumForceUpdateRoute {
  TO_DEFAULT = 'TO_DEFAULT',
  TO_CREATE = 'TO_CREATE',
}

export enum SocialModeTypes {
  CREATE = 'CREATE',
  CREATE_WIZARD = 'CREATE_WIZARD', //Create from wizard
  EDIT = 'EDIT',
  EDIT_DEV = 'EDIT_DEV',
}

export enum EnumAppScopeType {
  MORE_COMMERCE = 'MORE_COMMERCE',
  AUTO_DIGI = 'AUTO_DIGI',
  CRM = 'CRM',
  CMS = 'CMS',
}

export enum EnumWizardStepType {
  CMS_DEFAULT = 'CMS_DEFAULT',
  STEP_CONNECT_FACEBOOK = 'STEP_CONNECT_FACEBOOK',
  STEP_SET_SHOP_INFO = 'STEP_SET_SHOP_INFO',
  STEP_SET_LOGISTIC = 'STEP_SET_LOGISTIC',
  STEP_SET_PAYMENT = 'STEP_SET_PAYMENT',
  SETUP_SUCCESS = 'SETUP_SUCCESS',
}

export enum EnumPagesError {
  FB_PAGE_ALREADY_BINDED = 'FB_PAGE_ALREADY_BINDED',
}

export enum EnumWizardStepError {
  SETUP_FLOW_NOT_SUCCESS = 'SETUP_FLOW_NOT_SUCCESS',
  CANNOT_REMOVE_SETUP_SUCCESS_PAGE = 'CANNOT_REMOVE_SETUP_SUCCESS_PAGE',
  INVALID_WIZARD_STEP = 'INVALID_WIZARD_STEP',
}

export enum EnumOpenAPI {
  API_NOT_ACCESS = 'API_PERMISSION_DENIED',
  API_STATUS_DISABLED = 'API_STATUS_DISABLED',
  API_CLIENT_ID_OR_SECRET_INVALID = 'API_CLIENT_ID_OR_SECRET_INVALID',
  API_ACTIVE = 'API_ACTIVE',
  API_LINE_ACCESS_TOKEN_INVALID = 'API_LINE_ACCESS_TOKEN_INVALID',
}
