import { Dayjs } from 'dayjs';

export enum EnumAuthError {
  PAGE_APPLICATION_SCOPE_EMPTY = 'PAGE_APPLICATION_SCOPE_EMPTY',
  PAGE_APPLICATION_SCOPE_MISSING = 'PAGE_APPLICATION_SCOPE_MISSING',
  PAGE_APPLICATION_SCOPE_NOT_ALLOW = 'PAGE_APPLICATION_SCOPE_NOT_ALLOW',
  APPLICATION_SCOPE_NOT_ALLOW = 'APPLICATION_SCOPE_NOT_ALLOW',
  USER_APPLICATION_SCOPE_NOT_ALLOW = 'USER_APPLICATION_SCOPE_NOT_ALLOW',
  NO_SUBSCRIPTIONS = 'NO_SUBSCRIPTIONS',
  NO_SUBSCRIPTION_AT_INDEX = 'NO_SUBSCRIPTION_AT_INDEX',
  NO_PAGES = 'NO_PAGES',
  NO_PAGE_AT_INDEX = 'NO_PAGE_AT_INDEX',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  USED_TO_HAVE_SUB = 'USED_TO_HAVE_SUB',
  ALREADY_HAVE_SUB = 'ALREADY_HAVE_SUB',
  INVALID_SUBSCRIPTION_PLAN = 'INVALID_SUBSCRIPTION_PLAN',
  INVALID_SUBSCRIPTION_PLAN_ID = 'INVALID_SUBSCRIPTION_PLAN_ID',
  NO_SUBSCRIPTION_FROM_ID = 'NO_SUBSCRIPTION_FROM_ID',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAGE_REACHED_LIMIT = 'PAGE_REACHED_LIMIT',
  ALREADY_MEMBER_OTHER_EMAIL = 'ALREADY_MEMBER_OTHER_EMAIL',
  PACKAGE_INVALID = 'PACKAGE_INVALID',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  FB_PAGE_NOT_FOUND = 'FB_PAGE_NOT_FOUND',
  INVALID_TOKEN = 'INVALID_TOKEN',
  REQUEST_OTP_FAILED = 'REQUEST_OTP_FAILED',
  INACTIVE_USER = 'INACTIVE_USER',
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  PAGE_NOT_FOUND = 'PAGE_NOT_FOUND',
  UNKNOWN = 'UNKNOWN',
}

export enum EnumAuthScope {
  ADMIN = 'ADMIN',
  CMS = 'CMS',
  ADMIN_CMS = 'ADMIN_CMS',
  SOCIAL = 'SOCIAL', // SOCIAL === MORE-COMMERCE
  AUTODIGI = 'AUTODIGI',
}

export enum EnumLoginType {
  FACEBOOK = 'FACEBOOK',
  GOOGLE = 'GOOGLE',
  LINE = 'LINE',
  EMAIL = 'EMAIL',
}
export interface OpenAPIPayLoad {
  page_uuid: string;
  page_secret: string;
}

export interface WebviewSigned {
  hashKey: string;
  token: string;
  expiredIn: Dayjs;
}
export interface WebviewToken {
  token: string;
  expiredIn: Dayjs;
}
export interface WebviewTokenPayload {
  pageID: number;
  audienceID: number;
  subscriptionID: string;
  expiredIn: Dayjs;
}
