export enum MoreRouteAnimationEnum {
  LOGIN_PAGE = 'AnimatedPage',
  REGISTER_PAGE = 'RegisterPage',
  FORGET_PASSWORD_PAGE = 'ForgetPasswordPage',
  WELCOME_PAGE = 'WelcomePage',
  DASHBOARD_PAGE = 'DashboardPage',
  INBOX_PAGE = 'InboxPage',
  NOTIFICATION_PAGE = 'NotificationPage',
}

export enum CMSMobileRouteAnimationEnum {
  NOT_FOUND_PAGE = 'NotFoundPage',
  CONTENT_PAGE = 'ContentPage',
  CONTENT_DRAFT_PAGE = 'ContentDraftPage',
  CONTENT_DRAFT_NEW_PAGE = 'ContentDraftNewPage',
  CONTENT_DRAFT_EDIT_PAGE = 'ContentDraftEditPage',
  CONTENT_CONTENT_PAGE = 'ContentContentPage',
  CONTENT_CONTENT_EDIT_PAGE = 'ContentContentEditPage',
  CONTENT_FILE_MANAGE_PAGE = 'ContentFileManagePage',
  CONTENT_FILE_MANAGE_DETAIL_PAGE = 'ContentFileManageDetailPage',
  HOME_PAGE = 'HomePage',
  LOGIN_PAGE = 'LoginPage',
  EMAIL_LOGIN_PAGE = 'EmailLoginPage',
  FORGET_PASSWORD_PAGE = 'ForgetPasswordPage',
  ORDER_PAGE = 'OrderPage',
  ORDER_NEW_PAGE = 'OrderNewPage',
  ORDER_PAYMENT_PAGE = 'OrderPaymentPage',
  ORDER_SHIPPING_PAGE = 'OrderShippingPage',
  ORDER_FINISH_PAGE = 'OrderFinishPage',
  PRODUCT_PAGE = 'ProductPage',
  PRODUCT_CATEGORY_PAGE = 'ProductCategoryPage',
  PRODUCT_DETAILS_PAGE = 'ProductDetailsPage',
  PROFILE_PAGE = 'ProfilePage',
  PROFILE_NOTIFICATION_PAGE = 'ProfileNotificationPage',
  PROFILE_SETTING_PAGE = 'ProfileSettingPage',
  PROFILE_HELP_PAGE = 'ProfileHelpPage',
  PROFILE_LOGOUT_PAGE = 'ProfileLogoutPage',
}

export enum CMSRouteAnimationEnum {
  LOGIN_PAGE = 'LoginPage',
  WELCOME_PAGE = 'WelcomePage',
  WELCOME_INTRO_PAGE = 'WelcomeIntroPage',
  WELCOME_FEATURES_PAGE = 'WelcomeFeaturesPage',
  WELCOME_TEMPLATES_PAGE = 'WelcomeTemplatesPage',
  DASHBOARD_PAGE = 'DashboardPage',
  DASHBOARD_NEW_ORDER_PAGE = 'DashboardNewOrderPage',
  DASHBOARD_CONFIRM_PENDING_PAGE = 'DashboardConfirmPendingPage',
  DASHBOARD_SHIPPING_PENDING_PAGE = 'DashboardShippingPendingPage',
  DASHBOARD_FINISH_ORDER_PAGE = 'DashboardFinishOrderPage',
  DASHBOARD_LOW_STOCK_PAGE = 'DashboardLowStockPage',
  DASHBOARD_ACTIVE_USER_PAGE = 'DashboardActiveUserPage',
  DASHBOARD_ECOMMERCE_PAGE = 'DashboardECommercePage',
  DASHBOARD_ECOMMERCE_LOW_STOCK_PAGE = 'DashboardECommerceLowStockPage',
  DASHBOARD_AUDIENCE_PAGE = 'DashboardAudiencePage',
  SETTING_PAGE = 'SettingPage',
  SETTING_WEBSITE_PAGE = 'SettingWebsitePage',
  SETTING_ADMIN_PAGE = 'SettingAdminPage',
  SETTING_SHOP_PAGE = 'SettingShopPage',
  SETTING_MEMBER_PAGE = 'SettingMemberPage',
  SETTING_ADVANCE_PAGE = 'SettingAdvancePage',
  CMS_PAGE = 'CMSPage',
  CMS_EDIT_MODE_PAGE = 'CMSEditModePage',
  CMS_PREVIEW_MODE_PAGE = 'CMSPreviewModePage',
  CMS_PREVIEW_MOBILE_PAGE = 'CMSPreviewMobilePage',
  CMS_PREVIEW_DESKTOP_PAGE = 'CMSPreviewDesktopPage',
  CMS_PREVIEW_TABLET_PAGE = 'CMSPreviewTabletPage',
  SHORTCUT_CONTENT_MANAGEMENT_PAGE = 'DashboardContentManagementPage',
  SHORTCUT_FILE_MANAGEMENT_PAGE = 'DashboardFileManagementPage',
  SHORTCUT_PRODUCT_MANAGEMENT_PAGE = 'DashboardProductManagementPage',
  SHORTCUT_PRODUCTS_PAGE = 'DashboardProductsPage',
  SHORTCUT_SHOP_INFORMATION_PAGE = 'DashboardShopInformationPage',
  SHORTCUT_ORDER_MANAGEMENT_PAGE = 'DashboardOrderManagementPage',
  SHORTCUT_SHIPPING_SYSTEM_PAGE = 'DashboardShippingSystemPage',
  SHORTCUT_PAYMENT_SYSTEM_PAGE = 'DashboardPaymentSystemPage',
  SHORTCUT_PROMOTION_PAGE = 'DashboardPromotionPage',
  SHORTCUT_SALE_CHANNEL_PAGE = 'DashboardSaleChannelPage',
  SHORTCUT_TRASH_PAGE = 'DashboardTrashPage',
  SHORTCUT_INBOX_PAGE = 'DashboardInboxPage',
  SHORTCUT_TEMPLATE_SETTING_PAGE = 'DashboardTemplateSettingPage',
}
