export enum EnumUserError {
  CANT_GET_USER_FROM_FB = 'CANT_GET_USER_FROM_FB',
}

export enum EnumInvitedUserError {
  INVITE_ALREADY_ACCEPT = 'INVITE_ALREADY_ACCEPT',
  NO_PAGE_MEMBER_TOKEN_FOUND = 'NO_PAGE_MEMBER_TOKEN_FOUND',
  EMAIL_DIFFEREN = 'EMAIL_DIFFEREN',
  ALREADY_MEMBER_WITH_OTHER_EMAIL = 'ALREADY_MEMBER_WITH_OTHER_EMAIL',
  NO_INVITE_SUBSCRIPTION_FOUND = 'NO_INVITE_SUBSCRIPTION_FOUND',
}
