apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-api-_ENV_
  namespace: cms
spec:
  replicas: _SIZE_
  selector:
    matchLabels:
      app: cms-api-_ENV_
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cms-api-_ENV_
      annotations:
        'cluster-autoscaler.kubernetes.io/safe-to-evict': 'false'
    spec:
      containers:
        - name: cms-api-_ENV_
          image: git.itopplus.com:5000/cms/api:_TAG_
          imagePullPolicy: Always
          ports:
            - containerPort: 3335
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 3335
          readinessProbe:
            tcpSocket:
              port: 3335
          resources:
            requests:
              cpu: '125m'
              memory: '128Mi'
          env:
            - name: NODE_ENV
              value: '_ENV_'
            - name: MONGODB
              value: '_MONGODB_'
            - name: PG_URL_READ
              value: '_PG_URL_READ_'
            - name: PG_URL_WRITE
              value: '_PG_URL_WRITE_'
            - name: CMS_PUBLIC_KEY
              value: '_CMS_PUBLIC_KEY_'
            - name: CMS_PRIVATE_KEY
              value: '_CMS_PRIVATE_KEY_'
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: './assets/static/AUTH.json'
      imagePullSecrets:
        - name: gitlabsecret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: cms-api-_ENV_-service
  name: cms-api-_ENV_-service
  namespace: cms
  annotations:
    cloud.google.com/load-balancer-type: 'Internal'
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3335
  selector:
    app: cms-api-_ENV_
