apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-frontend-_ENV_
  namespace: cms
spec:
  replicas: _SIZE_
  selector:
    matchLabels:
      app: cms-frontend-_ENV_
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cms-frontend-_ENV_
      annotations:
        'cluster-autoscaler.kubernetes.io/safe-to-evict': 'true'
    spec:
      containers:
        - name: cms-frontend-_ENV_
          image: git.itopplus.com:5000/cms/frontend:_TAG_
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 80
          readinessProbe:
            tcpSocket:
              port: 80
      imagePullSecrets:
        - name: gitlabsecret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: cms-frontend-_ENV_-service
  name: cms-frontend-_ENV_-service
  namespace: cms
  annotations:
    cloud.google.com/load-balancer-type: 'Internal'
spec:
  type: LoadBalancer
  ports:
    - name: cms-frontend-_ENV_-port
      port: 8080
      targetPort: 80
  selector:
    app: cms-frontend-_ENV_
