apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-website-generator-_ENV_
spec:
  replicas: _SIZE_
  selector:
    matchLabels:
      app: cms-website-generator-_ENV_
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cms-website-generator-_ENV_
      annotations:
        'cluster-autoscaler.kubernetes.io/safe-to-evict': 'false'
    spec:
      containers:
        - name: cms-website-generator-_ENV_
          image: git.itopplus.com:5000/cms/website-generator:_TAG_
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '125m'
              memory: '128Mi'
          env:
            - name: NODE_ENV
              value: '_ENV_'
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: './assets/AUTH.json'
      imagePullSecrets:
        - name: gitlab
