apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-website-generator-handler-_ENV_
spec:
  replicas: _SIZE_
  selector:
    matchLabels:
      app: cms-website-generator-handler-_ENV_
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cms-website-generator-handler-_ENV_
      annotations:
        'cluster-autoscaler.kubernetes.io/safe-to-evict': 'false'
    spec:
      containers:
        - name: cms-website-generator-handler-_ENV_
          image: git.itopplus.com:5000/cms/website-generator-handler:_TAG_
          imagePullPolicy: Always
          ports:
            - containerPort: _PORT_
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: _PORT_
          readinessProbe:
            tcpSocket:
              port: _PORT_
          resources:
            requests:
              cpu: '125m'
              memory: '128Mi'
          env:
            - name: NODE_ENV
              value: '_ENV_'
            - name: PORT
              value: '_PORT_'
          volumeMounts:
            - name: cce-efs-import-storage-cms-pv
              mountPath: '/fileStorage'
      imagePullSecrets:
        - name: gitlab
      volumes:
        - name: cce-efs-import-storage-cms-pv
          persistentVolumeClaim:
            claimName: cce-efs-import-storage-cms
